src/css/layui.css

更新layui.css

---

src/lay/modules/layedit.js

/**
* 设置编辑器内容
* @param {[type]} index   编辑器索引
* @param {[type]} content 要设置的内容
* @param {[type]} flag    是否追加模式
*/

增加setContent方法.

---

test/lay/modules/laydate.js
test/layui.js

计划是先把文档中的配置、方法覆盖了, 然后再写根据页面交互功能的测试~

添加laydate测试

---

bower.json

fix bower error

---

test/lay/modules/code.js

1. 经测试发现 <https://github.com/sentsin/layui/blob/master/src/lay/modules/code.js#L36> 这一个条件永远会进入, 因为在 <https://github.com/sentsin/layui/blob/master/src/lay/modules/code.js#L34> 这一行重写了整个 `pre` 标签, 导致 `> .layui-code-h3` 元素肯定不存在
2. 发现 `lay-about="false"` 不起作用

add code test case

---

examples/form.html

修改 form 示例中邮箱类型错误

---

karma.conf.sauce.js

chore: 修改浏览器配置

---

.travis.yml
test/layui.js

1. fix: 修复 `layui.sort` 参数默认值更新
1. chore: 修改浏览器和 sauce 顺序

fix: 修改测试报错

---

src/lay/modules/table.js

modified:   src/lay/modules/table.js

Support post+json for table module

---

src/modules/laydate.js

1. laydate 修复点击页面的其他区域无法关闭已经打开的日期选择面板的问题
2. laydate 事件触发时候添加限制，避免trigger为click已经弹出面板的时候点选触发节点中的文本的时候日期选择面板闪一下的问题

Fix some issues with laydate

---

src/modules/carousel.js

carousel autoplay新增'always'支持

---

src/modules/table.js

issues：https://gitee.com/sentsim/layui/issues/I5E270

紧急修复2.7.0引入的table组件触发console报错的问题

---

examples/json/table/demo1.json
examples/table-test.html
src/layui.js
src/modules/table.js

- table
- [调整] obj.update() 方法，不再对其他模板列自动更新，采用 reloadData 自主控制

2.7.3.beta.1

---

examples/laydate.html
src/css/modules/laydate/default/laydate.css
src/modules/laydate.js

日期控件添加中国法定节假日及补班标注

---

src/modules/table.js

数据表格ajax请求增加jsonp相关参数

---

src/modules/form.js
src/modules/table.js

1.  form 修复添加了validate之后导致带有lay-verify=""的节点之后的验证都不会被校验的问题 [I5EU9Z](https://gitee.com/sentsim/layui/issues/I5EU9Z)
2.  table 修复reloadData之后没有数据或者接口异常的情况下没有更新全选框状态的问题 [I5F6NJ](https://gitee.com/sentsim/layui/issues/I5F6NJ)

修复table和form的一些问题

---

src/modules/table.js

table 修复打印带有复杂表头的表格出现的错列问题[I5EXPW](https://gitee.com/sentsim/layui/issues/I5EXPW)

修复table打印错列的问题

---

examples/form.html
examples/table-test.html
src/modules/form.js
src/modules/table.js

- table: [修复] 合计行自定义模板后，未优先读取后端返回的合计数据的问题

修复合计行的一个小问题

---

docs/index.html

增加 docs 中转页

---

package.json

更新 package.json

---

src/modules/table.js

当列超出屏幕范围、并且 无数据（或请求异常） 时 table组件底部没有横向滚动条，以至于无法看到剩余的列。增加底部滚动条，以便查看所有的列

---

examples/table-test.html
examples/table.html
src/css/layui.css
src/modules/lay.js
src/modules/laydate.js
src/modules/table.js

- table
- 新增 cellMaxWidth 属性和表头 maxWidth 属性，以设定列的最大宽度
- 新增 colResized 列拖拽宽度后的事件，并返回当前列的相关信息 # I3URH8/I3QDBI
- 新增 colToggled 列筛选（显示或隐藏）后的事件，并返回当前列的相关信息 # I3URH8
- 新增 返回数据中的 data 成员为非对象时的渲染支持，如 `data: ["a","b","c"]`
- 修复 头工具栏筛选下拉面板被下方表格遮挡的问题，并重新优化了表格内部层级关系 #763
- 优化 事件的回调参数，可返回当前实例配置项：config
- 优化 edit 事件的核心逻辑，返回参数中新增 `reedit` 方法，可实现编辑内容校验不通过时重新显示编辑
- 优化多处代码核心
- other
- 见 commit 描述

改进 table 组件大量核心

---

examples/dropdown.html
examples/element.html
examples/util.html
src/modules/dropdown.js
src/modules/element.js
src/modules/util.js

- util
- 重构 util.fixbar 组件
- 新增 fixbar 的 bars 属性，用于定义可显示的 bar 列表信息
- 新增 fixbar 的 default 属性，用于是否显示默认的 bar 列表
- 新增 fixbar 的 target 属性，用于定义插入 fixbar 节点的目标元素选择器(默认 body)
- 新增 fixbar 的 on 属性，用于定义按钮的任意事件
- element
- 修复 `element.progress()` 方法不支持更新分数值的问题 #622
- dropdown
- 新增 clickScope 属性，用于设置触发点击事件的菜单范围(如 `all` 即代表父子菜单均可触发事件) 

改进 util fixbar 等其他组件

---

examples/all.html
gulpfile.js
package.json
src/layui.js
src/modules/code.js
src/modules/laydate.js
src/modules/layer.js

- 优化代码构建 
- 修改 模块 css 加载路径判断
- 更新 version：v2.8.0-beta.1
- 剔除 layedit 内置模块

进一步优化代码构建，适配 v2.8.x

---

examples/table-test.html
src/modules/laydate.js
src/modules/table.js

- table
- 优化 templet 表头属性函数时返回的数据可包含 `LAY_COL` 特定属性

优化 table templet 表头属性细节

---

src/css/modules/laydate.css
src/layui.js
src/modules/laydate.js
src/modules/layer.js
src/modules/table.js

- laydate 修复主题丰富修改之后导致当前选中的高亮日期在鼠标获焦之后背景颜色异常问题
- laydate 新增shortcuts参数，支持在面板的左侧列出部分常用的选项提供快速操作 [测试链接](https://codepen.io/sunxiaobin89/pen/MWVByKx)
- layer 修复多次调用min或者max方法之后执行restore还原之后出现的异常问题 [I5QP66](https://gitee.com/layui/layui/issues/I5QP66)
- layer 修复最大化之后窗口大小调整之后弹窗的大小异常问题 [I5ROMW](https://gitee.com/layui/layui/issues/I5ROMW)
- layer 修复最大最小之后如果窗口的大小出现变化，恢复原来状态之后可能出现的不居或者大小异常问题
- layer 修复最小化之后恢复原始大小之后window resize之后弹窗的位置异常问题
- table 修复table.init方法将静态表格转成数据表格的过程中，如果thead是比较一些比较特殊的复杂表头，同时存在默认的tbody数据的时候出现的错列问题 [I5QAZM](https://gitee.com/layui/layui/issues/I5QAZM)
- table 修复针对数据异常包括无数据的时候对tbody的样式修改对之后数据正常如果出现窗口大小发生改变之后出现字段宽度异常问题
- table 修复exportFile导出任意数据的时候出现的异常问题 [I5S17X](https://gitee.com/layui/layui/issues/I5S17X)
- table …

修复一些问题及新增一些功能

---

src/modules/layer.js

layer.prompt({
formType: 2,
value: decodeURI(link_content),
title: '请输入视频号ID和视频ID（各一行）',
placeholder: '视频号ID:\n视频ID:'  // 在这里添加了placeholder属性的支持
}, function(value, index, elem){
// Do something
layer.close(index);
});

layer.prompt的文本框添加placeholder

---

src/modules/dropdown.js
src/modules/laydate.js
src/modules/table.js

- dropdown render返回的信息中添加remove方法，方便调用关闭弹出的下拉菜单 [I5S7XZ](https://gitee.com/layui/layui/issues/I5S7XZ)
- laydate 调整继承节点上lay-options属性的逻辑，让单个渲染的时候也支持
- laydate 新增autoConfirm是否自动确认配置，默认true,在非range的日期/年份/月份选择器的时候可以控制点击对应的选项之后默认确认，部分场景下希望保持一致只有用户点击确认按钮才算确认选中该值 [I5T3GW](https://gitee.com/layui/layui/issues/I5T3GW)  [测试链接](https://codepen.io/sunxiaobin89/pen/mdLXYpr)
- table 修复之前调整init的方法导致如果在init中传入data最终出来的结果其优先级小于tbody中的节点数据的问题（2.8正式版更新信息不需要提及）。

修复几个小问题以及新增一些功能

---

docs/README.md
src/css/layui.css

- 新增 grid 布局的超大屏(xl)响应式支持
- 优化 input 动/静态套件的鼠标移入时的形状
-  新增 docs 相关说明

2.8.0-beta.3 的几处细节改进

---

src/css/modules/layer.css
src/modules/layer.js

- layer 修复closeBtn: 2的样式异常问题 [I5UJL8](https://gitee.com/layui/layui/issues/I5UJL8)  [测试链接](https://codepen.io/sunxiaobin89/pen/VwxERGR)
- layer 修复鼠标右键点击部分节点的影响，比如弹窗的可移动选择节点（如标题栏）的时候触发了一些事件，导致一些右键的功能触发之后弹窗位置大小的异常问题
- layer 调整prompt,支持输入空值，prompt的功能简单化提供一个输入框，一般来说不需要太多的限制比如空值，比如限制了不允许空值的话无法做到对原始有值的覆盖，如果有需要校验再做处理可在yes回调中处理 [I5UO7N](https://gitee.com/layui/layui/issues/I5UO7N)
- layer 优化弹出之后对弹出前聚焦节点的焦点处理，避免在弹出一个弹窗之后按回车键依旧触发了弹窗外的一些节点的事件，msg，load和tips是特殊的信息层，默认不让原始焦点节点失焦，也可通过新增的属性removeFocus控制

优化layer的一些细节

---

examples/dropdown.html
examples/laydate.html
src/css/layui.css
src/css/modules/laydate.css
src/modules/dropdown.js
src/modules/laydate.js

- laydate 和 dropdown 添加遮罩 shade ; 以便支持在 div 出现滚动条时, 不随滚动条滚动的问题;

laydate 和 dropdown 添加遮罩 shade ; 以便支持在 div 出现滚动条时, 不随滚动条滚动的问题;

---

src/css/modules/laydate.css

因浏览器缩放导致双日历左右宽度不够换行

---

src/modules/layer.js

ref: https://gitee.com/layui/layui/pulls/91
STAUTS_NAME -> STATUS_NAME

Fix var name typo

---

src/modules/transfer.js

- input的type=input，修改为type=text

input的type属性修改

---

src/layui.js
src/modules/rate.js

- 删除if大括号后面的分号，同一个文件里，编码风格建议统一

删除分号，同一个文件里，编码风格建议统一

---

README.md
preview.yml

docs: add Cloud IDE preview link

---

src/modules/laydate.js

- laydate修复点击确认时进入done回调的时候参数错误问题 [I65DS6](https://gitee.com/layui/layui/issues/I65DS6) [测试链接](https://codepen.io/sunxiaobin89/full/MWVByKx)
因为新增属性的需要在移除控件的过程中会删除一些属性，原先的逻辑先移除组件之后再执行done，导致在done的处理中部分属性不存在了进而出现反馈中的现象，重新调整remove和done的顺序，先执行完毕再移除控件

laydate修复点击确认时进入done回调的时候参数错误问题

---

src/modules/table.js

方便在表格行上使用`layui.dropdown`组件
- 增加监听行的上下文菜单事件
- 增加是否显示系统默认上下文菜单事件的配置 `options.defaultContextmenu`

增加行的上下文菜单事件

---

README.md

更新readme文件中JS和CSS的Brotli size图标在github中无法显示问题。

---

src/modules/form.js

- 优化 form 匹配复选框和单选框的正则表达式，使更严谨

优化 form 匹配复选框和单选框的正则表达式

---

gulpfile.js

细调 Gulp task 注释的文字间距

---

docs/layout/index.md

- 更新 `docs/layout/index.md`，admin 布局右侧菜单动画修改为 `slideLeft`

更新 `docs/layout/index.md`，admin 布局右侧菜单动画修改为 `slideLeft`

---

src/css/layui.css
src/modules/treeTable.js

- 修复 treeTable showIcon为false的时候折叠图标跟标题有一个空白的问题
- 修复 treeTable 自动排序且是url取数的时候树表渲染失效的问题

修复 treeTable 的一些问题

---

docs/table/index.md

hideCol的第二个参数实际是做了多种形式的适配，可以根据需要灵活传参应对不同的场景需求，支持显示或隐藏单列字段，同时操作多列的显示和隐藏，也支持直接显示或隐藏所有列
- 完善 table 关于 `hideCol` 用法示例
hideCol的第二个参数实际是做了多种形式的适配，可以根据需要灵活传参应对不同的场景需求，支持显示或隐藏单列字段，同时操作多列的显示和隐藏，也支持直接显示或隐藏所有列

完善 table 关于 `hideCol` 用法示例

---

docs/icon/index.md

- 文档图标点击复制  [演示](https://sight-wcg.github.io/layui-doc/#/docs/icon/index)
**如果编译为 HTML 后无法使用或有其他影响，请随时关闭该 PR**

新增文档图标点击复制

---

src/modules/table.js

- 修复数据表格在不启用分页的时候底边框缺失问题
- 修复前
- 修复后

修复数据表格在不启用分页的时候底边框缺失问题

---

docs/color/index.md

color 文档优化

---

docs/versions.md

添加 v2.8.3 更新日志

---

src/modules/form.js

- 修复 form 重新渲染时 checkbox 自定义模版未正确获取的问题，关闭 [I76Y16](https://gitee.com/layui/layui/issues/I76Y16)
演示： https://stackblitz.com/edit/pm1uam?file=index.html
更新了演示

修复 form 重新渲染时 checkbox 自定义模版未正确获取的问题

---

.gitee/ISSUE_TEMPLATE/bug.yml
.gitee/ISSUE_TEMPLATE/feature.yml

增加 Gitee issue 表单范式

---

.gitee/ISSUE_TEMPLATE/bug.yml
.gitee/ISSUE_TEMPLATE/feature.yml

添加 Gitee issue  表单模板

---

src/modules/laydate.js

- 修复 laydate 开启面板联动区间，并设置主题色时，现在时间格子的颜色非主题色的问题，关闭 [I75N6O](https://gitee.com/layui/layui/issues/I75N6O)
- 支持将 laydate theme 选项的第二个自定义颜色作为辅助色(应用在区间选中，鼠标悬停等)，关闭 [I75N6O](https://gitee.com/layui/layui/issues/I75N6O)
演示： 
- [before](https://starsatdawn.gitee.io/code-play/#eNq1VU9v3EQU/yoTs9LuKus1AQWVrXeFRDggIcGBC8JImdjP62lsjzUz3jZarRTUEwTRA0UcmqhqUSEcSpBAKohI/TJ4k3wL3ozt/ZNs2/RQX+bN+/9+897z2PJ5AFZvbN2iIyp9wTKlbz5PFaRIWjHdy1k3l9AK89RXjKet9tgTXkrIiAqC4oAqIH1NoWJ1vznXaMxkjZLpOGT605Pp4cPz7+4WD/4iNime/VLc+/Pi6PH06Pn51/eLb48v9r+ZHvw2PX5UnN4rrSrHXQFpAKJVpUAIC3qepUAqz+rUPIgh6ZHmWx9v2ZWZLWg6hE9YugtBc6ZnmD3y5ZKmVFQo25Abzc6yF4xdS75a9lK67hElcphJVARJ6X8D3g/DsNmZWyEKfmTiX8HVCPWn4WNBH3MwANZpNNdVxGSXIRB3KqCXTKTai/WLNFosaHdD1Gs1Da/ZvqRtuF0Fd1RrgWyT9Ut6hGw3xiyYkPp9bYkY+wqCQcBG4x3q7w4FzxE …

新增 laydate 辅助色设置

---

src/modules/table.js

- 修复 [table hideCol](https://layui.dev/docs/2.8/table/#table.hideCol) 方法第二个参数为对象时无效的问题，关闭 [I7AAUN](https://gitee.com/layui/layui/issues/I7AAUN)  |  [演示](https://starsatdawn.gitee.io/code-play/#eNqdVltPG0cU/iuD+7C2tOu1uRizBdQK+pCnVm1fqjiq9nJsD6x3rd2xjWtZopdUSBSI1EZVVFKaBBSkCojaCmhKkj/jXcJT/0LP7IyxjZM+5MG7M+fyzbl8e8adlO07kDI6qRWzaYZ2QOuM72zfY+DhMpXqqqkqq7mj0vmJ5Y+XPv/ik48I1y2WvHn55iswHVwRMl8DZhK7agYhsIVSqsHKWrGUGtJ5Zg1Q0aTQqvsBK6WIPAKFLeqw6oIDTWqDlmxUQj3KqOlqoW26sJDvYzHKXFhchpo/r4t1Ip7QNPL65CzafBXtHl49+vvyl+P46El0sXO5fRI9/rZ3fhRd3L/86fD1yQFxzXaDZu0wJNHus+jhOtE0AeJSb5VUAyhjSLre8Oqrlazt1/TE4YPJbDE7rTs0ZDr6CiFHwUwCcNElZG0XwioAJsfLpMvq4NLynbaM37RcILZrhiG6JCBalTqAKLjRytRlEKCGQchrRB1c31rWEjfNwbQ1LPCnfmupCvYqOHgS1oErBbxoK2HtOi82gzWm8271kRIA5vuuZQZjQBwAIRzavBGfxTyNN8ukHgTXhmhqN …

修复 table hideCol 方法第二个参数为对象时无效的问题

---

src/modules/element.js

- 修复 tab 组件 `layui-tab-title` 中有其他元素时，li 获取错误的下标，导致点击删除按钮对应的 tab-content 未删除的问题，关闭 [I7AO7F](https://gitee.com/layui/layui/issues/I7AO7F) | [演示](https://starsatdawn.gitee.io/code-play/#eNqVVVtvG0UU/ivTfbENWa9t4tI4TgVqeEQg0RekvIx3Zr2TzM5au7N2o2DJEi0pSlVeCiWhlLYQESHiRAIVN03Jn/H68sRf4Mzs+pILAvzgPXNu853vnLO7Zdg+oUZly1jHTRzaAWtIdbJ9IakA0TDaC4YrPX5eW722+tGt259+/AFStptropo+lUQxAQmhqkclRraLg5DKlTUjko55Y82YswnsUTA0GW01/ECuGSi9ApQtRqS7QmiT2dTUhwXEBJMMczO0MacrxUkuySSnN1ep51etRNbqa6aJRkd/xDtn8ZOD8fNXw++6g8Mf49Ovhg+P4hef93uH8enXw0cHo6N9xPFmxPJ2GKL4yXH8fQeZZpKEM7GB3IA6AMmyItHYqOdt37N0wHul/I38okVYKC2ITZQqC1QSUA4hodzkNHQpheIUTVbKDog1n2wmdxDWRDbHYQgBOoUpcQ1SgGw6jEsagEHSUJouFoTT1IQ591s290PFoQwi0Ot8kDHilxOampqpD3ixC04M2E+Y0KIp6B2APXFHSBcD3lBvA9wqTAA71Kxx395YbtJAMugLwGJ1UUEeIwB12cNBnQkzYH …

修复 tab 组件 `layui-tab-title` 中有其他元素时，li 获取错误的下标，导致点击删除按钮对应的 tab-content 未删除的问题

---

.gitee/ISSUE_TEMPLATE/bug.yml

优化 Gitee issue 表单模板

---

src/modules/element.js

修复 tab 索引获取错误
- 修复 tab 索引获取错误 
[I7AWNV](https://gitee.com/layui/layui/issues/I7AWNV)
[演示](https://starsatdawn.gitee.io/code-play/#eNqVVM1u00AQfpWtL0mlOKu0CU2CGyFRziDBBTUcNvYk3nTjjbzrhCqKhISAAxJc4ESR+BFSL225QaUKXgY35S2Y9U/SlkhVLt7Zb+Ybz8zOzMRypQdWc2L12YgpN+RDbW6uDDQEKFrWtGT5eiCuos7azv27jx4/uEeMrtUOnPkJzMOTEGcAmhHXZ6ECvd22It21623rki5gA0DFiMN4KEPdtkj2AwTH3NP+tgcj7oKdXEqEB1xzJmzlMgHbldyX5lpAawcG0qGpnMBrtk0uTn7Er3/HB4d/P5/OPhyfH32Nz97O3pzEX57/+XkUn72fvTu8OPlGBNuPeNlVisQH3+OPz4htp04ED/aIH0IXQ6I0CoZ7vbIrBzQh3Nko18s16nGlKXJT0HjBTEIQSFF6X4DyATA5UxyaVcfpSG/fnMMQiCuYUmic0G3zHsjHiy2HmsvAqCZoZ8rUJDqMoGS0MtJNslvIFIUSKRhm4UmJaCmFMrpuJIQBPBlAk3SjwDX+irLTX5+Y7FAohxB4EBbXb7eD6XReUXiqWQjMROjx0bUINetkATIh5NgVUplnNJHlDiLxP8dO3iazSEp73cbnWLnW+adXs6NfFYcKvjDN0I2l6OZStLoUrc1Rh0amYVFYmiI+RNKL …

修复 tab 索引获取错误

---

src/modules/form.js

- [ x ] 功能优化
- select lay- search下拉框显示时，删除input的文本方便输入，不用再手动删除文本
- [ x ] 已对每一项的改动均测试通过

layui-select搜索筛选，删除input已有文本并放入 placeholder，方便输入

---

examples/upload.html
gulpfile.js
package.json
src/modules/upload.js

优化部分代码的书写规范

---

.gitee/ISSUE_TEMPLATE/bug.yml
.gitee/ISSUE_TEMPLATE/config.yml
.gitee/ISSUE_TEMPLATE/feature.yml
docs/form/checkbox.md
docs/form/examples/form.demo.md
docs/modules.md
docs/table/detail/demo.md
docs/table/examples/search.md
docs/table/examples/setRowChecked.md
docs/table/index.md

- 优化 Gitee Issue 模板
- 优化 文档多处细节

优化 Gitee Issue 模板和文档细节

---

docs/util/detail/demo.md

- 优化 util 文档，demo 开启 iframe 模式  [I7FG1Q](https://gitee.com/layui/layui/issues/I7FG1Q) 

优化 util 文档

---

docs/dropdown/detail/options.md

- 优化 docs/dropdown/detail/options.md 文档，关闭 [#I7J7B6](https://gitee.com/layui/layui/issues/I7J7B6)

优化 docs/dropdown/detail/options.md 文档

---

docs/laydate/detail/options.md
docs/laydate/examples/shortcut.md
src/modules/laydate.js

- laydate 快捷选择 shortcuts.value 选项支持函数类型，解决 [I7TLYJ](https://gitee.com/layui/layui/issues/I7TLYJ)
[演示](https://codepen.io/Sight-wcg/pen/poqoVwP)

laydate 快捷选择 shortcuts.value 选项支持函数类型

---

src/modules/table.js

优化table.js代码

---

src/modules/table.js

修复复选框状态都为“禁用 ”时，表头的复选框仍可以点击操作。

---

src/modules/treeTable.js

优化代码，修复节点禁止状态时半选全选问题

---

src/modules/table.js

table.js增加了小提示^_^

---

src/modules/code.js

修复 code 自定义工具栏异常

---

src/modules/treeTable.js

解决异步加载数据没有子节点数据双点行展开已展开的所有节点问题

解决异步加载数据没有子节点数据双点行展开已展开的所有节点问题

---

src/modules/layer.js

photos增加旋转，翻转，放大，缩小功能

---

src/css/modules/layer.css

增加photo工具栏样式

---

docs/layer/index.md

增加了顶部工具栏说明

---

src/modules/rate.js

优化 rate.js 代码

---

src/modules/code.js

修复Code组件非安全域复制失败问题

---

src/css/modules/code.css

修复code组件全屏时Preview无法滚动问题

---

src/modules/upload.js

修复参数和变一致问题

---

src/css/layui.css

优化lay-affix="number"验证失败颜色不同的问题

---

docs/layer/index.md

增加layer.closeAll,layer.close 方法参数说明

---

src/modules/carousel.js

> 请至少勾选一项
- 优化轮播组件动画效果，修复 [I82STP](https://gitee.com/layui/layui/issues/I82STP)
【演示】https://stackblitz.com/edit/web-platform-vuefvf?file=index.html

优化轮播组件动画效果

---

src/modules/treeTable.js

> 请至少勾选一项
- 修复 treeTable 组件 treeTable.setRowChecked 未逐层展开上级节点的问题，关闭 [I84RUT]( https://gitee.com/layui/layui/issues/I84RUT)
[![Open in StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/web-platform-zd8xms?file=index.html)

修复 treeTable 组件 treeTable.setRowChecked 未逐层展开上级节点的问题

---

docs/treeTable/index.md

> 请至少勾选一项
- treeTable/index.md 修改错别字

更新 treeTable/index.md

---

src/modules/table.js

> 请至少勾选一项
- 修复 table 在 IE 下同时开启多行模式和单元格编辑时，输入框高度异常的问题。~~也可能解决 [I853YX](https://gitee.com/layui/layui/issues/I853YX)~~ 不能
Before
After

修复 table 在 IE 下同时开启多行模式和单元格编辑时，输入框高度异常的问题

---

docs/index.md

优化 `docs/index.md` 示例代码

---

src/modules/element.js

> 请至少勾选一项
[![Open in StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/web-platform-isbxqe?file=index.html)
- nav-menu
- 修复快速点击时，折叠图标未正确切换的问题
- 修复快速点击时，展开项变为固定高度，影响子菜单展开的问题

优化 nav 垂直导航展开收缩的动画效果

---

src/css/modules/code.css

> 请至少勾选一项
- 修复 [I88ZMQ](https://gitee.com/layui/layui/issues/I88ZMQ)

优化 code 预览显示效果

---

src/modules/lay.js

> 请至少勾选一项
- 增加 lay 模块部分函数的注释，关闭 [I89V5M](https://gitee.com/layui/layui/issues/I89V5M)

增加 lay 模块部分函数注释

---

examples/element.nav.html
src/css/layui.css
src/modules/element.js

重构 nav 垂直导航菜单展开收缩动画

---

gulpfile.js
package.json

> 请至少勾选一项
- [I89W5P](https://gitee.com/layui/layui/issues/I89W5P)

新增 Source Maps 支持

---

src/modules/dropdown.js

> 请至少勾选一项
- 重构 dropdown 动画，和 nav 保持一致的动画效果
[演示] https://stackblitz.com/edit/web-platform-ivfowk?file=index.html

重构 dropdown 动画

---

src/modules/table.js

修复表头属性type:'radio', fixed: 'right'时选择效果无效问题，但是不影响数据返回

---

src/modules/lay.js

> 请至少勾选一项
- 修复 `lay.elem` 注释中参数类型错误

修复 `lay.elem` 注释中参数类型错误

---

src/modules/table.js

> 请至少勾选一项
- 修复 table complete 选项未设置时仍生效的问题，修复 [I8GP73](https://gitee.com/layui/layui/issues/I8GP73)
【演示】https://stackblitz.com/edit/web-platform-hcrej6?file=index.html

修复 table complete 选项未设置时仍生效的问题

---

docs/table/examples/editModes.md

> 请至少勾选一项
- 优化 table 文档多样化编辑示例，示例中的自定义 table.getRowData 改为和内置 API 风格一致，对新手更友好。关联 [I8GQGV](https://gitee.com/layui/layui/issues/I8GQGV)

优化 table 文档多样化编辑示例

---

src/modules/colorpicker.js

> 请至少勾选一项
- 优化 colorpicker 内部输入框取值，移除字符串两侧的空白字符。关闭 [I8BA01](https://gitee.com/layui/layui/issues/I8BA01)
[演示]https://stackblitz.com/edit/web-platform-kqj1om?file=index.html

优化 colorpicker 内部输入框取值，移除字符串两侧的空白字符

---

docs/table/examples/editModes.md

> 请至少勾选一项
- 优化 table 文档, #1424 有一些缺陷，此场景自己写事件委托反而更麻烦

优化 table 文档

---

src/modules/tree.js

> 请至少勾选一项
- 修复 tree 节点 title 有特殊字符时的显示问题，解决 [I8K79H](https://gitee.com/layui/layui/issues/I8K79H)
[演示]https://stackblitz.com/edit/web-platform-pnkvoq?file=index.html

修复 tree 节点 title 有特殊字符时的显示问题

---

docs/laypage/detail/options.md
src/modules/laypage.js

> 请至少勾选一项
- 新增 laypage countText 选项，关闭 [#I8LQZL](https://gitee.com/layui/layui/issues/I8LQZL)
[演示]https://stackblitz.com/edit/wyjrwb?file=index.html

新增 laypage countText 选项

---

src/modules/layer.js

> 请至少勾选一项
- 优化 layer.tips 在触发元素高度较小时的定位
close https://gitee.com/layui/layui/issues/I8KZ9A
[演示]https://stackblitz.com/edit/web-platform-8hgtac?file=index.html

优化 layer.tips 在触发元素高度较小时的定位

---

.github/workflows/npm-publish.yml

> 请至少勾选一项
- 自动执行 `npm publish`

新增 NPM 自动发布工作流

---

src/modules/table.js

#1438
> 请至少勾选一项
- 修复 table 在 IE 下报错

修复 table 在 IE 下报错

---

src/modules/form.js

> 请至少勾选一项
- 修复 select 在 IE10 和 11 中的兼容性问题，
close #1449
https://caniuse.com/input-placeholder

修复 select 在 IE10 和 11 中的兼容性问题

---

docs/dropdown/detail/options.md
src/modules/dropdown.js

close https://gitee.com/layui/layui/issues/I8NZ8X
> 请至少勾选一项
- 增强 dropdown delay 选项，支持设置 `显示/隐藏` 的延迟时间
因为显示时有一段过渡动画，所以显示的延迟需要略小一些
[演示]https://stackblitz.com/edit/wyjrwb-gixfp9?file=index.html

feat(dropdown): 增强 dropdown delay 选项，支持设置 `显示/隐藏` 的延迟时间

---

.github/workflows/issue-close-require.yml
.github/workflows/issue-labeled.yml
.github/workflows/release.yml
SECURITY.md

> 请至少勾选一项
- 新增 Issue 标签管理与自动关闭
- 新增 release 根据 tag 自动发行
- 新增 Security Policy

chore: 新增 issue, release 工作流

---

.github/workflows/issue-labeled.yml

ci(issue): 剔除部分 label 的自动回复

---

src/css/layui.css

style: 优化输入框圆角时后缀存在方框的问题

---

.github/ISSUE_TEMPLATE/bug-feature.yml
.github/workflows/issue-close-require.yml
.github/workflows/issue-closed.yml
.github/workflows/issue-labeled.yml
.github/workflows/issue-opened.yml
.github/workflows/release.yml

> 请至少勾选一项
- [新增 Issue 创建和编辑时的 action](https://github.com/layui/layui/commit/3347067a61557ded8f22a7924b8b3b2779046dbe)
- [新增 Issue 关闭时的 action](https://github.com/layui/layui/commit/0d3ab187415d4643ea40c110c5edbb450893da0d)
- [修改 issue 不活跃状态天数](https://github.com/layui/layui/commit/ff6ac096e99a8a21109fd0b542baebc4cde810fe)
- [增加 issue 模板特定标识](https://github.com/layui/layui/commit/30c6b3f6483b2f4d9184c6df31de56e4a41c37c6)
- 其他若干细节优化

ci(issue): 新增和优化多个 workflow

---

src/modules/lay.js
src/modules/rate.js

> 请至少勾选一项
- 修复 carousel 移动端滑动切换后，点击箭头切换异常的问题
- 修复 rate 移动端滑动时，评分对应的文本未更新的问题

fix(touch): 修复移动端 rate, carousel 一些小问题

---

.github/workflows/issue-close-require.yml
.github/workflows/issue-labeled.yml
.github/workflows/issue-opened.yml

ci: 优化 issue 被创建和被编辑时的 action 校验逻辑

---

docs/upload/detail/options.md
src/modules/upload.js

> 请至少勾选一项
- upload 组件 data 选项的函数写法支持获取文件相关数据
解决 https://gitee.com/layui/layui/issues/I8JAC1
[演示]https://stackblitz.com/edit/pxvk9j?file=index.html

feat(upload):upload 组件 data 选项的函数写法支持获取文件相关数据

---

.github/ISSUE_TEMPLATE/bug-feature.yml

docs: 优化 issue 模板提示文案

---

src/modules/form.js

> 请至少勾选一项
- 粘贴文本时打开搜索面板
[演示]https://stackblitz.com/edit/orsrjb-wvjxbw?file=index.html

chore(select): 优化搜索面板打开逻辑

---

docs/transfer/detail/options.md
src/modules/transfer.js

> 请至少勾选一项
- feat(transfer): 新增 `dblclick` 选项
[演示]https://stackblitz.com/edit/orsrjb-yr1r8w?file=index.html

feat(transfer): 新增 `dblclick` 选项

---

src/modules/table.js

> 请至少勾选一项
- fix(table): 非常规列设置 `field` 时，导出 excel 合计行错位，解决 [I8PHCR](https://gitee.com/layui/layui/issues/I8PHCR)

fix(table): 非常规列设置 `field` 时，导出 excel 合计行错位

---

docs/slider/detail/demo.md
docs/slider/detail/options.md
examples/slider.html
src/css/layui.css
src/modules/slider.js

> 请至少勾选一项
- 新增 silder 提示文本始终显示控制属性

feat(silder): 新增提示文本始终显示控制属性

---

src/modules/laydate.js

> 请至少勾选一项
- fix(laydate): 优化时间选择器在 Safari on iOS, Firefox for Android 中的滑动操作
resolve https://github.com/layui/layui/issues/1533

fix(laydate): 优化时间选择器在 Safari on iOS, Firefox for Android 中的滑动操作

---

docs/table/detail/options.cols.md
docs/table/index.md
src/modules/table.js

> 请至少勾选一项
- feat(table): 新增 `table.updateRow` 方法
[演示]https://stackblitz.com/edit/orsrjb-vkcdbs?file=index.html
closes  #1483, #1538

feat(table): 新增 `table.updateRow`方法

---

src/modules/dropdown.js
src/modules/layer.js
src/modules/laypage.js

> 请至少勾选一项
- 将 Unicode 编码转换为中文字符

chore: 将 Unicode 编码转换为中文字符

---

src/modules/table.js

close #1590
> 请至少勾选一项
- table禁止拖拽列宽后仍可拖拽
close #1590

fix(table): 禁止拖拽列宽后仍可拖拽

---

src/modules/layer.js

chore: typo

---

docs/table/detail/options.md

docs(table): 添加缺失的引号

---

src/modules/layer.js

> 请至少勾选一项
- fix(layer): height 设置为 auto，恢复大小时内容区高度错误
close #1604
https://stackblitz.com/edit/orsrjb-mgw9eq?file=index.html

fix(layer): height 设置为 auto，恢复大小时内容区高度错误

---

docs/dropdown/detail/options.md
examples/dropdown.html
src/modules/dropdown.js

> 请至少勾选一项
- 新增 close 选项。close #1603
https://stackblitz.com/edit/orsrjb-g7ig9f?file=index.html

feat(dropdown): 新增 close 选项

---

docs/flow/detail/options.md
src/modules/flow.js

> 请至少勾选一项
- feat(flow): 新增 direction 选项
https://stackblitz.com/edit/orsrjb-mzzfrj?file=index.html

feat(flow): 新增 direction 选项

---

docs/layer/index.md
src/modules/layer.js

> 请至少勾选一项
- feat: type 支持数组类型
- feat: 不指定 type 时, 将从所有类型的层中寻找最近打开的
- fix: 捕获层关闭顺序错误
close #1651 
https://stackblitz.com/edit/orsrjb-yl3kxq?file=index.html

refactor: 优化 layer.closeLast

---

docs/form/index.md
docs/form/select.md
src/modules/form.js

> 请至少勾选一项
- feat(form-select):  支持创建新 option
https://stackblitz.com/edit/orsrjb-n4cim1?file=index.html
close #1581

feat(form-select):  支持创建新 option

---

src/modules/layer.js

> 请至少勾选一项
- 优化最大/小化，恢复大小后宽高偶现细微差异的问题。这会导致布局错位或者出现滚动条。
https://stackblitz.com/edit/orsrjb-udjf4u?file=index.html

fix(layer): 优化最大/小化，恢复大小后宽高偶现细微差异的问题

---

src/css/modules/laydate.css
src/modules/laydate.js

> 请至少勾选一项
- 时间选择器根据 format 格式显隐
close #1646
https://stackblitz.com/edit/orsrjb-wvtrwz?file=index.html

feat(laydate): 时间选择器根据 format 格式显隐

---

src/modules/slider.js

> 请至少勾选一项
- feat(slider): step 支持小数
close #1582
https://stackblitz.com/edit/orsrjb-brgd1x?file=index.html

feat(slider): step 支持小数

---

docs/form/index.md

> 请至少勾选一项
- 优化文档：删除form属性lay-creatable描述里多余的右括号。

docs(form): 删除多余的右括号

---

src/modules/form.js

> 请至少勾选一项
- fix(form-select): lay-creatable 在旧版微软拼音输入法下无法创建中文 option 的问题
close #1666 

fix(form-select): lay-creatable 旧版微软拼音输入法兼容性问题

---

docs/layer/examples/more.md

> 请至少勾选一项
- 优化文档：layer 页面锁屏示例禁用右下角拉伸尺寸

docs(layer): 页面锁屏示例禁用右下角拉伸尺寸

---

docs/dropdown/index.md
examples/dropdown.html
src/modules/dropdown.js

> 请至少勾选一项
- feat(dropdown): 新增 dropdown.open 方法

feat(dropdown): 新增 dropdown.open 方法

---

src/modules/table.js

> 请至少勾选一项
- fix(table): 优化单元格展开按钮的显示判断  close #1698
该 PR 可以不用写入更新日志，因为 .laui-table-cell 是 border-box 且无边框，大多数情况 outerWidth() 和 clientWidth 是相等的，只是能避免某些边缘情况。

fix(table): 优化单元格展开按钮的显示判断

---

src/modules/laydate.js

> 请至少勾选一项
- 优化 holidays 日期对比，现在可以处理日期数字前置 0 的情况  closes #1718
https://stackblitz.com/edit/zz7spu?file=index.html

feat(laydate): 优化 holidays 日期对比

---

src/modules/treeTable.js

> 请至少勾选一项
- fix(treeTable): 表格所有行删除后，再次添加新行失败
close #1753 

fix(treeTable): 表格所有行删除后，再次添加新行失败

---

src/modules/treeTable.js

> 请至少勾选一项
- fix(treeTable): 表格删除所有行之后，全选按钮选中的问题
close #1753

fix(treeTable): 表格删除所有行之后，全选按钮选中的问题

---

src/modules/dropdown.js

> 请至少勾选一项
- 将 dropdown id 添加到触发元素，可以简化 table 中的封装，无需额外处理固定列
ref: https://github.com/layui/layui/issues/1748

chore(dropdown): 将 dropdown id 添加到触发元素

---

src/modules/treeTable.js

> 请至少勾选一项
- fix(treeTable): 添加和删除节点时，未更新节点图标的问题
close #1785
https://stackblitz.com/edit/zz7spu-fc52jx?file=index.html

fix(treeTable): 添加和删除节点时，未更新节点图标的问题

---

src/modules/table.js

> 请至少勾选一项
table 中添加 resizeObserver，在 tab 中使用 table 时，现在无需惰性渲染或执行 table.resize

feat(table): 添加 resizeObserver

---

src/modules/treeTable.js

> 请至少勾选一项
- fix(treeTable): 删除子节点时，未更新 isParent Key 的问题
ref: https://github.com/layui/layui/pull/1784#issuecomment-2056271982
https://stackblitz.com/edit/zz7spu-mte9ta?file=index.html

fix(treeTable): 删除子节点时，未更新 isParent Key 的问题

---

src/modules/form.js

> 请至少勾选一项
- fix(form-select): 修复 XSS 漏洞
close #1810
https://stackblitz.com/edit/bs2swu-2ggqfa?file=index.html

fix(form-select): 修复 XSS 漏洞

---

src/modules/table.js

> 请至少勾选一项
- fix(treeTable): 节点移动后，行索引获取错误
close #1815
https://stackblitz.com/edit/zz7spu-xgmcg3?file=index.html

fix(treeTable): 节点移动后，行索引获取错误

---

src/modules/laydate.js

> 请至少勾选一项
- fix(laydate): 日期时间选择器，点击时间时 change 回调未触发
close #1713

fix(laydate): 日期时间选择器，点击时间时 change 回调未触发

---

src/modules/treeTable.js

> 请至少勾选一项
- fix(treeTable): 重载时格式化图标异常,  #1808 导致的问题
- fix(treeTable): 异步加载节点异常，#1792 导致的问题

fix(treetable): 修复 treeTable 由 #1808，#1792 导致的一些问题

---

src/modules/tree.js

fix(tree): 修复编辑节点标题时的 xss 问题

---

docs/upload/detail/options.md
src/modules/upload.js

> 请至少勾选一项
- feat(upload): choose 回调的参数中新增 getChooseFiles 方法
closes #1543 #1803 #1671

feat(upload): choose 回调的参数中新增 getChooseFiles 方法

---

src/css/layui.css

> 请至少勾选一项
- fix(colorpicker): 优化游标显示
close #1817

fix(colorpicker): 优化游标显示

---

src/modules/element.js

> 请至少勾选一项
- fix(element.tab): 改进自定义 tab 的索引获取
close #1789
https://stackblitz.com/edit/p13wct?file=index.html

fix(element.tab): 改进自定义 tab 的索引获取

---

src/modules/flow.js

> 请至少勾选一项
- feat(flow): 重复执行 flow.load 时，解除旧的事件
close #1822

feat(flow): 重复执行 flow.load 时，解除旧的事件

---

docs/laydate/detail/options.md
src/modules/laydate.js

> 请至少勾选一项
- refactor(laydate): 将 mark 和 holidays 选项函数类型的第一个参数由数组改为对象

refactor(laydate): 将 mark 和 holidays 选项函数类型的第一个参数由数组改为对象

---

docs/laydate/detail/demo.md
docs/laydate/detail/options.md
docs/laydate/examples/cell.md
src/modules/laydate.js

> 请至少勾选一项
- feat(laydate): 新增 cellRender 选项，用于自定义单元格内容
https://stackblitz.com/edit/web-platform-qp41bp?file=index.html

feat(laydate): 新增 cellRender 选项，用于自定义单元格内容

---

src/css/layui.css
src/modules/colorpicker.js

> 请至少勾选一项
- fix(colorpicker): 优化游标显示效果
close #1817
https://stackblitz.com/edit/p13wct-orrg99?file=index.html
在 IE 10 仿真中测试通过
1.修复游标溢出
2.游标在滑动区域的四个角落时，溢出隐藏的范围保持一致

fix(colorpicker): 优化游标显示效果

---

src/modules/form.js

fix(form): 修复 form.val() 为 radio 设置布尔值时的失效问题

---

examples/treeTable-async.html
examples/treeTable-crud.html
src/modules/table.js
src/modules/treeTable.js

> 请至少勾选一项
- fix(table): 修复 2.9.9 table.setRowChecked 无效的问题
close #1911

fix(table): 修复 2.9.9 table.setRowChecked 的参数中， index 选项为数组时，无法选中的问题

---

examples/json/treeTable/demo-simple.json
examples/treeTable.html
src/modules/treeTable.js

> 请至少勾选一项
- perf(treeTable): 改进 flatToTree 性能

perf(treeTable): 改进 flatToTree

---

src/modules/colorpicker.js

> 请至少勾选一项
- fix(colorpicker): 优化游标滑动效果
close #1922
https://stackblitz.com/edit/ik4tug?file=index.html

fix(colorpicker): 优化游标滑动效果

---

src/modules/treeTable.js

> 请至少勾选一项
- fix(treeTable): treeTable data 模式非深度重载时，如果 reload 参数中没有 data 选项，会清除表格数据的问题
close #1936
https://stackblitz.com/edit/x61zk4-kqqwyl?file=index.html

fix(treeTable): treeTable data 模式非深度重载时，如果 reload 参数中没有 data 选项，会清除表格数据的问题

---

src/modules/layer.js

> 请至少勾选一项
- 修复 layer.alert 在一些浏览器的兼容模式下报错无法弹出的问题;

fix(layer): 修复 layer.alert 在一些浏览器的兼容模式下报错无法弹出的问题;

---

docs/upload/detail/options.md
src/modules/upload.js

> 请至少勾选一项
- feat(upload): before 选项的返回值支持 Promise 和 Deferred Promise 对象类型
close #1831
https://stackblitz.com/edit/vu45xk-hsqxxh?file=index.html

feat(upload): before 选项的返回值支持 Promise 和 Deferred Promise 对象类型

---

docs/table/examples/editModes.md

> 请至少勾选一项
- docs(table): 优化多样化编辑原生select事件
https://github.com/layui/layui/discussions/1774#discussioncomment-9077177
https://github.com/layui/layui/discussions/1941#discussioncomment-9532853

docs(table): 优化多样化编辑原生select事件

---

docs/flow/detail/options.md
src/modules/flow.js

> 请至少勾选一项
- feat(flow): 流加载支持"加载更多"按钮文案自定义
- close #1960

feat(flow): 流加载支持"加载更多"按钮文案自定义

---

docs/layer/detail/options.md
src/modules/layer.js

> 请至少勾选一项
- feat(layer): 新增 beforeEnd 回调
close #1798

feat(layer): 新增 beforeEnd 回调

---

src/modules/colorpicker.js

> 请至少勾选一项
1. 修复移动端颜色选取异常， 由 #1923 导致
2. 修复移动端游标无法拖动的问题

fix(colorpicker): 修复移动端颜色选取异常

---

docs/upload/detail/options.md
src/modules/upload.js

> 请至少勾选一项
- feat(upload): error回调函数增加返回值参数
- close #1925 

feat(upload): error回调函数增加返回值参数

---

docs/layer/detail/demo.md
docs/layer/detail/options.md
docs/layer/examples/btnasync.md
src/css/modules/layer.css
src/modules/layer.js

> 请至少勾选一项
- feat(layer): 新增 btnAsync 选项
https://stackblitz.com/edit/vu45xk-xvjlq2?file=index.html  

feat(layer): 新增 btnAsync 选项

---

docs/laydate/detail/options.md

docs(laydate): 修改日期组件 isInitValue 默认值

---

docs/form/index.md
docs/form/select.md
docs/table/examples/editModes.md
src/css/layui.css
src/modules/form.js
src/modules/lay.js

> 请至少勾选一项
- feat(form-select): 新增 `lay-append-to-body` 属性
https://stackblitz.com/edit/vu45xk-qgzw4k?file=index.html

feat(form-select): 新增 `lay-append-to` 属性

---

src/modules/laydate.js

> 请至少勾选一项
https://stackblitz.com/edit/stackblitz-starters-gppxlj?file=index.html

fix(laydate): 修复日期范围联动模式中，点击任意面板的边缘日期时，另一侧面板未能正确切换的问题

---

src/modules/treeTable.js

> 请至少勾选一项
- fix(treetable)：修复 treeTable.reloadAsyncNode 重载节点异常,
close #2011

fix(treetable)：修复 treeTable.reloadAsyncNode 重载节点异常

---

src/css/modules/laydate.css

> 请至少勾选一项
https://stackblitz.com/edit/7nvqsg?file=index.html

style(laydate): 优化选中主题色

---

src/css/layui.css
src/modules/form.js
src/modules/table.js

> 请至少勾选一项
- perf(table): 优化表格数据量较大时行选中性能
https://stackblitz.com/edit/web-platform-xe7cpl?file=index.html
ref: https://github.com/layui/layui/pull/1443

perf(table): 优化表格数据量较大时行选中性能

---

docs/table/detail/options.md
docs/table/examples/demo.md
examples/table-test.html
src/modules/table.js

> 请至少勾选一项
- 重构 `defaultToolbar` 选项，增加 `onClick` 事件，可自定义文件导出等操作
https://stackblitz.com/edit/h31q9x?file=index.html

refactor(table): 重构 defaultToolbar 选项

---

docs/form/select.md

> 请至少勾选一项
remove 会移除面板上的事件，导致无法选中 option

docs(form-select): 更新文档

---

src/modules/table.js

> 请至少勾选一项
- fix(treeTable): 有展开的节点时无法全选的问题
https://stackblitz.com/edit/tzptv5?file=index.html

fix(treeTable): 有展开的节点时无法全选的问题

---

src/modules/dropdown.js

> 请至少勾选一项
- fix(dropdown): 重复 render 时未 reload

fix(dropdown): 重复 render 时未 reload

---

src/modules/table.js

> 请至少勾选一项
- closes #2031
https://codepen.io/layui/pen/zYQRZew

fix(treeTable): 修复 cols 的 exportTemplet 函数导出异常的问题

---

src/modules/form.js
src/modules/table.js

> 请至少勾选一项
- fix(form-select): 改进自动更新 UI, close #2032
https://stackblitz.com/edit/pszywd-soc9fu?file=index.html
toggleClass 第二个参数仅接受 boolean 类型，非 boolean 类型会直接忽略

fix(form-select): checked 属性设置为非 boolean 类型的值时，UI 更新异常

---

src/modules/carousel.js

> 请至少勾选一项
- fix(carousel): 修复切换按钮会触发form表单submit事件的问题
- close #2053 

fix(carousel): 修复切换按钮会触发form表单submit事件的问题

---

src/modules/table.js

> 请至少勾选一项
上个版本 #2019 导致。修改后的正常显示：

fix(table): 修复无数据时，点击右上角工具栏图标出现提示错位的问题

---

src/modules/form.js

> 请至少勾选一项
- fix(form-radio): 改变 checked 属性值时，UI 更新异常
https://stackblitz.com/edit/pszywd-kayv2t?file=index.html

fix(form-radio): 改变 checked 属性值时，UI 更新异常

---

src/modules/form.js

> 请至少勾选一项
- feat(form-select): 改进 select 搜索，支持非连续，乱序字符匹配  close #2055
https://stackblitz.com/edit/pszywd-yuit96?file=index.html

feat(form-select): 改进 select 搜索，支持非连续，乱序字符匹配

---

examples/carousel.html
src/modules/carousel.js

> 请至少勾选一项
- 修复动态删除条目至最后一个时调用 inst.reload 的异常问题。
closes #2102
Preview: https://stackblitz.com/edit/m7fw8a?file=index.html

fix(carousel): 修复动态删除条目至最后一个时调用 inst.reload 的异常问题

---

docs/tab/index.md
src/modules/element.js

> 请至少勾选一项
- feat(element-tab): 新增 tab 切换前的事件 close #2071
- feat(element-tab): 优化 tabChange 添加 skipBeforeChange 参数 
- docs(element-tab): 更新 tabChange 和 tabBeforeChange 相关文档
Preview: https://stackblitz.com/edit/upetcr?file=index.html

feat(element-tab): 新增 tab 切换前的事件

---

src/css/layui.css

style: 优化 layui-text 细节，以更好地适应 Markdown

---

docs/index.md

docs: 文档与示例日常微调

---

src/modules/upload.js

feat(upload): error 回调函数新增第四个参数： xhr 对象

---

docs/nav/index.md
docs/panel/index.md
docs/progress/index.md
docs/tab/index.md
src/modules/element.js

> 请至少勾选一项
- feat(element): 支持指定元素渲染
close #2148
https://stackblitz.com/edit/pszywd-b5kaa1?file=index.html

feat(element): 支持指定元素渲染

---

src/modules/table.js

> 请至少勾选一项
- revert #1773
close #2168
打开页面后，拖动任意一列以改变列宽
https://stackblitz.com/edit/2hpqvf-mdkusd?file=index.html

revert #1773

---

src/modules/form.js

> 请至少勾选一项
- fix(form-select): 修复由 #2138 导致的移动端无法选中问题
close #2180 
https://stackblitz.com/edit/zuevjz?file=index.js
在 stackblitz 预览界面上方点击「在新选项卡中打开预览」按钮，然后用开发者工具中的设备仿真进行测试。

fix(form-select): 修复由 #2138 导致的移动端无法选中问题

---

src/modules/table.js

> 请至少勾选一项
- fix(table): 优化慢速网络下表头列宽
close #2204
需要在本地测试，在开发者工具网络选项卡中选择慢速网络

fix(table): 优化慢速网络下表头列宽

---

src/modules/flow.js

> 请至少勾选一项
- fix(flow): 回滚 #1852 中加载时自动清除绑定元素内容的改动
close #2217
https://stackblitz.com/edit/6ocnos?file=index.js

fix(flow): 回滚 #1852 中加载时自动清除绑定元素内容的改动

---

src/modules/dropdown.js

> 请至少勾选一项
- fix(dropdown): 修复移动端遮罩层点击穿透问题
close #2189
https://stackblitz.com/edit/nstpf6

fix(dropdown): 修复移动端遮罩层点击穿透问题

---

src/modules/table.js

> 请至少勾选一项
移植了 #1726 一部分代码，原来的核心计算逻辑基本不变，需要拉取到本地测试
- fix(table): 修复表格列宽计算问题
close #2185
https://stackblitz.com/edit/jpiw5g?file=index.js

fix(table): 修复表格列宽计算问题

---

src/modules/table.js

> 请至少勾选一项
- fix(table): 重载时若当前页超过总页数，序号列渲染异常
close #2240
https://stackblitz.com/edit/3wuq9m-gjdbq8?file=index.js

fix(table): 重载时若当前页超过总页数，序号列渲染异常

---

src/modules/layer.js

> 请至少勾选一项
- 修复与 layui.js 中的 `getPath` 方法相似的问题

fix(layer): 修复 layer.path 潜在的缺陷

---

src/css/layui.css
src/modules/table.js

> 请至少勾选一项
- fix(table): 修复列宽分配一些边缘情况
已在 Chrome，Firefox，IE 8 仿真中测试通过。close #2244 close #2248 fix #2168
https://stackblitz.com/edit/gnp9x1?file=2187.html

fix(table): 修复表格列宽计算一些边缘情况

---

src/css/layui.css
src/modules/table.js

> 请至少勾选一项
- fix(table): 修复 table 在 Firefox 浏览器中偶现行闪烁的问题
close #2259

fix(table): 修复 table 在 Firefox 中偶现行闪烁的问题

---

docs/layer/detail/options.md
src/modules/layer.js

> 请至少勾选一项
- fix(layer): 改进 maxWidth 和 maxHeight 的处理
close #2213
https://stackblitz.com/edit/7xmwur-mjrlap?file=index.html

fix(layer): 改进 maxWidth 和 maxHeight 的处理

---

src/modules/laydate.js

feat(laydate): 增加类型为 date 或 datetime 时点击年列表换到月选择器功能

---

docs/dropdown/detail/options.md
src/modules/dropdown.js

> 请至少勾选一项
- feat(dropdown): click 回调中传递事件对象
close #2269

feat(dropdown): click 回调中传递事件对象

---

src/modules/table.js

> 请至少勾选一项
fix(table): 改进表格自动调整大小的处理
close #2282
https://stackblitz.com/edit/noxlsj?file=index.js

fix(table): 改进表格自动调整大小的处理

---

src/css/layui.css
src/modules/table.js

> 请至少勾选一项
- fix(table): 修复由 #2250 造成的右侧固定列偏移 1 像素问题
https://stackblitz.com/edit/kgrfr3?file=index.html

fix(table): 修复由 #2250 造成的右侧固定列偏移问题

---

src/modules/table.js

> 请至少勾选一项
- feat(table): 使固定列的滚动更平滑
已在 IE8 测试
https://stackblitz.com/edit/jfz3f3?file=index.html

feat(table): 使固定列的滚动更平滑

---

examples/util.html
src/modules/util.js

> 请至少勾选一项
- closes #2351
- Preview：https://stackblitz.com/edit/zi7feq?file=index.html,index.js

fix(util): 修复 `util.on()` 多个并列使用时，同一委托元素的 `trigger` 冲突问题

---

src/modules/table.js

> 请至少勾选一项
- fix(table): 修复 table 在没有大小的容器中渲染时列宽异常
close #2370
https://stackblitz.com/edit/hvwwwz?file=index.js

fix(table): 修复 table 在没有大小的容器中渲染时列宽异常

---

docs/class/index.md
examples/layout-admin.html
examples/text.md.html
src/css/layui.css

> 请至少勾选一项
- 剔除 .layui-body 不必要的 z-index，提升内部 fixed 布局灵活度
- 优化 .layui-text 文本类，以更好地适应 Markdown 渲染后的文档

chore: 优化 .layui-body 和 .layui-text 样式细节

---

src/modules/colorpicker.js

#1863
> 请至少勾选一项
- fix(colorpicker): 修复颜色值错误
close #2397
https://stackblitz.com/edit/qt416fxz?file=index.html

fix(colorpicker): 修复颜色值错误

---

gulpfile.js

> 请至少勾选一项
- 剔除多余的 `version` 参数
- 通过 `vs` 参数生成特定版本号

build(gulp): 优化 vs 参数

---

src/modules/table.js

> 请至少勾选一项
- closes #2221
[演示]：https://stackblitz.com/edit/bxgpvzfv?file=index.html

fix(table): 修复未正确导出合计行模板的问题

---

examples/treeTable.html
src/modules/element.js

> 请至少勾选一项
- fix(nav): 导航菜单在 IE 中的兼容性问题

fix: 修复 nav 在 IE 中的兼容性问题

---

src/modules/table.js

> 请至少勾选一项
- feat(table): 重新添加 ResizeObserver
https://stackblitz.com/edit/1yifyz87?file=index.html

feat(table): 重新添加 resizeObserver

---

docs/treeTable/index.md

> 请至少勾选一项
- docs(treeTable): 更新 treeTable.checkStatus 文档
close #2424

docs(treeTable): 更新 treeTable.checkStatus 文档

---

docs/code/detail/options.md
src/modules/code.js

> 请至少勾选一项
- feat(code): : 支持获取复制状态，阻止默认提示
close #2391
https://stackblitz.com/edit/pwpjjsrq?file=index.html

feat(code): 支持获取复制状态，阻止默认提示

---

src/modules/form.js

> 请至少勾选一项
- fix(form): form.val 获取 multiple select 值错误
close #2422
https://stackblitz.com/edit/hprx82xa?file=index.js

fix(form): form.val 获取 multiple select 值错误

---

src/modules/form.js

> 请至少勾选一项
- feat(form): 相同 name 的 checkbox，将值序列化为数组
ref https://github.com/layui/layui/issues/2359  https://github.com/layui/layui/discussions/2074 https://gitee.com/layui/layui/issues/I83Y15
[演示]https://stackblitz.com/edit/fgy352ki?file=index.html
```jsx
<div class="layui-input-block">
<input type="checkbox" name="like" value="write" title="写作">
<input type="checkbox" name="like" value="read" title="阅读">
<input type="checkbox" name="like" value="daze" title="发呆">
</div>
// 赋值
form.val('filter', {
like: ['write', 'read'] // value 包含于数组值的 checkbox 将被选中
})
// 取值
form.val('filter')  =>  {like: ['write', 'read']} // 未选中返回 null
```

feat(form): 相同 name 的 checkbox，将值序列化为数组

---

src/layui.js
src/modules/lay.js
src/modules/table.js

> 请至少勾选一项
- fix(table): 修复 table 在 IE8 下报错问题
IE8 currentStyle.getAttribute 接受 camelCase  形式的字符参数，IE8 仿真环境接受 camelCase 和 kebab-case 形式字符串参数。
现在 layui.getStyle 第二个参数同时支持 camelCase 和 kebab-case 形式。
close #2430
将下面的代码复制到本地，在真实的 IE8 中测试
```html
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Demo</title>
<link href1="../src/css/layui.css" href="//unpkg.com/layui@2.9.21-rc/dist/css/layui.css" rel="stylesheet">
</head>
<body>
<table class="layui-hide" id="ID-table-demo-search"></table>
<script src1="../src/layui.js"
src="//cdn.jsdelivr.net/gh/layui/layui@cf713f995055e3877a06bf3b696b2987f2dc345c/src/layui.js"></script>
<script>
layui.use(function () {
var table = layui.table;
var form = layui.form;
var laydate = …
```

fix(table): 修复 table 在 IE8 下报错问题

---

src/modules/form.js
src/modules/lay.js

> 请至少勾选一项
- fix(form): 修复 form.val 第二个参数为 ArrayLike 时表单赋值异常
close #2454
https://stackblitz.com/edit/iwspwtsf?file=index.html

fix(form): 修复 form.val 第二个参数为 ArrayLike 时表单赋值异常

---

src/modules/treeTable.js

> 请至少勾选一项
- fix(treeTable): 异步加载子节点失败后，无法点击重新加载
close #2476
https://stackblitz.com/edit/qshusisw-xi5f7wmk?file=package.json

fix(treeTable): 异步加载子节点失败后，无法点击重新加载

---

src/modules/table.js

revert #2411

---

src/modules/form.js

fix(form): 修复赋值

---

src/css/modules/code.css

> 请至少勾选一项
- fix(code): 修复选项卡底边框重叠问题
close #2516
相对定位元素仍然占据原来的空间，使用 `top:-1px` 会在组件底部产生非预期的间隙

fix(code): 修复选项卡底边框重叠问题

---

src/modules/treeTable.js

> 请至少勾选一项
- fix(treeTable): 修复 treeToFlat 改变根节点 pid 问题  close #2507

fix(treeTable): 修复 treeToFlat 改变根节点 pid 问题

---

src/modules/table.js
src/modules/treeTable.js

> 请至少勾选一项
修复 checkbox 重复更新，大约能提升 30% 性能
[演示]https://stackblitz.com/edit/h9npfynt?file=index.js

fix(treeTable): 修复 checkbox 重复更新

---

.github/ISSUE_TEMPLATE/bug-feature.yml

> 请至少勾选一项
- 更新 bug-feature.yml，添加标题格式
例如
[table] 表格能否支持自定义请求

chore: 更新 bug-feature.yml，添加标题格式

---

src/modules/layer.js

> 请至少勾选一项
- fix(layer): 改进设置页面滚动条逻辑
close #2534
https://stackblitz.com/edit/j8zepdb3

fix(layer): 改进设置页面滚动条逻辑

---

docs/form/input.md
src/css/layui.css
src/modules/form.js

> 请至少勾选一项
- 非有效数字时输入框显示值变为红色，警示无效输入
- 输入框类型为 type = 'text' 时，限制允许输入的字符
- 新增 `lay-wheel` 属性，是否启用滚轮或触摸板事件处理，对齐原生 input
- 新增 `lay-step-strictly` 属性，步长严格模式，只能输入步长的倍数
close #2372
[演示]https://stackblitz.com/edit/stvf4d3b?file=index.html
https://stackblitz.com/edit/mgz4yihh?file=package.json

fix(form-input-number): 限制允许输入的字符

---

examples/util.html
src/modules/util.js

> 请至少勾选一项
- fix(util): `util.toDateString` 规范化字符串日期
close #2541
https://stackoverflow.com/questions/2587345/why-does-date-parse-give-incorrect-results

fix(util): `util.toDateString` 规范化字符串日期

---

src/modules/layer.js

fix(layer): 修复在 success 中关闭上一个弹层报错的问题

---

docs/carousel/detail/options.md

boolean类型必须且只能有两个互斥的状态，此处anim类型一共有三个不同的值，需要使用字符串类型。
> 请至少勾选一项
- [√] 问题修复
- 修正了 carousel 文档中的 anim类型，应该是string类型而不是boolean类型
- [√] 已提供在线演示地址（如：[codepen](https://codepen.io/), [stackblitz](https://stackblitz.com/)）或无需演示
- [√] 已提供具体的变化内容说明

docs: 修正 carousel 文档中的 anim 类型

---

docs/class/index.md
src/css/layui.css

类名 layui-elip 修改为 layui-ellip，以符合业界及官方文档中通常的拼写形式
> 请至少勾选一项
- 类名 layui-elip 修改为 layui-ellip，以符合业界及官方文档中通常的拼写形式

fix: 修正 layui-ellip 类名简写

---

docs/component/index.md

> 请至少勾选一项
更正 component 文档中的拼写错误，elem中“组件”缺少了组字

docs: 更正 component 文档中的漏写错误

---

src/css/layui.css

fix: 修复 `body` 初始 `line-height` 无效的问题

---

docs/index.md
docs/tabs/examples/custom.md
docs/tabs/examples/demo.md
docs/versions.md

docs: 优化文档细节

---

src/modules/table.js

> 请至少勾选一项
- fix(table): 修复竞态问题
close #2304

fix(table): 修复竞态问题

---

docs/form/index.md
examples/form.html
src/css/layui.css
src/modules/form.js

> 请至少勾选一项
lay-ignore 支持设置在父元素上。
- 修改ignore的判断逻辑；
- 增加ignore的开发案例；
https://github.com/layui/layui/issues/2582

feat(form): 优化 lay-ignore 的判断逻辑

---

src/modules/form.js

fix(form): 修复 input 设置 `lay-vertype="tips"` 验证时 tips 层定位异常问题

---

src/css/layui.css

style(card): 优化 card 面板头部样式，去除高度限制

---

src/css/layui.css
src/modules/tabs.js

fix(tabs): 修复 box-sizing 对主体区域中其他组件的样式影响

---

src/modules/laypage.js

fix(laypage): 优化快速点击时文本被选中的问题

---

docs/rate/index.md
examples/rate.html
src/modules/rate.js

> 请至少勾选一项
- 由 component 模块重构 rate 代码结构，组件原有逻辑未变

refactor: 重构 rate 组件，由 component 模块构建

---

docs/laytpl/detail/demo.md
src/modules/laytpl.js
src/modules/util.js

> 请至少勾选一项
```js
// 之前
layui.util.escape('&#xe7d6;'); // &#xe7d6;
layui.util.escape('&lt;'); // &lt;
// 之后
layui.util.escape('&#xe7d6;'); // &amp;#xe7d6;
layui.util.escape('&lt;'); // &amp;lt;
```
```js
// 预期返回：&lt;script&gt;alert("yo")&lt;/script&gt;
// 修复前实际返回：<script>alert("yo")</script>
// 修复后实际返回：&lt;script&gt;alert("yo")&lt;/script&gt;
layui.util.unescape('&amp;lt;script&amp;gt;alert("yo")&amp;lt;/script&amp;gt;');
```

fix: 优化 escape 和 unescape 在解析某些特殊字符串时的潜在问题

---

src/modules/form.js
src/modules/lay.js

> 请至少勾选一项
- feat(form-select): select 点击外部关闭支持检测 iframe
- feat(lay): lay.onClickoutside 新增 detectIframe 选项
- feat(lay): lay.touchSwipe 新增 preventDefault 选项
有时需要禁用内部的 preventDefault，例如 https://github.com/layui/layui/issues/1799
https://stackblitz.com/edit/9dyneycg?file=index.html

feat(form-select): select 点击外部关闭支持检测 iframe

---

src/css/modules/code.css
src/css/modules/laydate.css
src/css/modules/layer.css

> 请至少勾选一项
- 清理 laydate, layer 组件中 IE 低版本 css hack

style(css): 清理 IE 低版本 css hack

---

src/modules/component.js

fix(component): 优化 render, events 执行的条件

---

src/layui.js

> 请至少勾选一项
-  path → pathname 与 `layui.url` 一致。`path` 将在合适的版本移除

chore(hash): 新增返回 pathname, 与 layui.url 一致

---

src/modules/table.js
src/modules/transfer.js

> 请至少勾选一项
- 避免表格和穿梭框受全局 laytpl tagStyle 影响渲染异常

fix(table): 避免表格和穿梭框受全局 laytpl tagStyle 影响渲染异常

---

src/modules/laytpl.js

> 请至少勾选一项
- 增强 template 报错时的上下文捕获，基于映射，可更精确定位到具体错误行

feat(laytpl): 增强 template 报错时的上下文捕获

---

src/css/layui.css

> 请至少勾选一项
- 将轮播组件中的部分 `left` `top` 属性改为 `transform` 以此提高性能和降低页面 CLS (前者作为几何属性改动需要重新计算样式, 而后者不是则不需要)

perf(carousel): 使用 transform 改善性能

---

src/css/layui.css
src/modules/element.js

feat(collapse): 新增折叠面板展开和收缩时的过渡动画

---

src/modules/laydate.js

> 请至少勾选一项
- fix(laydate): 修复 `range:false, autoConfirm:false` 时确认按钮状态同步异常
https://stackblitz.com/edit/qgqwgzmj?file=index.js
close #2753

fix(laydate): 修复 `range:false, autoConfirm:false` 时确认按钮状态同步异常

---

src/css/layui.css

> 请至少勾选一项
- fix(laypage): 移除 laypage 中 input 元素的过渡效果
close #2787

fix(laypage): 移除 laypage 中 input 元素的过渡效果

---

docs/table/detail/options.ajax.md
src/modules/table.js
src/modules/treeTable.js

> 请至少勾选一项
- feat(table): 支持自定义 ajax 请求
https://stackblitz.com/edit/poddikxq?file=index.js
close #2751
close #2381
close #1648
close #1807 
close #1889
close #2265
close #2536

feat(table): 支持自定义 ajax 请求

---

docs/slider/index.md
src/modules/slider.js

> 请至少勾选一项
- refactor(slider): 使用 component 重构 slider  
close #2738
https://stackblitz.com/edit/xbkwvqff?file=index.html

refactor(slider): 使用 component 重构 slider

---

src/modules/dropdown.js
src/modules/form.js
src/modules/lay.js

> 请至少勾选一项
- fix(select): 元素大小变化时重新定位
close #2817
https://stackblitz.com/edit/sfehzkzh?file=index.html

fix(select): 面板元素大小变化时重新定位

---

src/modules/form.js
src/modules/table.js

> 请至少勾选一项
- fix(checkbox): 优化和 label 元素的兼容性问题
close #2833
https://stackblitz.com/edit/wpgmmu9n?file=index.js

fix(table): 修复 checkbox/radio 列触发行事件问题

---

src/modules/laydate.js

> 请至少勾选一项
- fix(laydate): 预览区域选中高亮跟随主题
close #2822

fix(laydate): 预览区域选中日期时，高亮颜色跟随主题

---

src/modules/dropdown.js
src/modules/form.js
src/modules/lay.js

> 请至少勾选一项
- feat(dropdown): 支持同时打开多个
- fix(dropdown): 元素大小变化时重新定位
close #2439
这个 PR 基于 #2824，应该在其之后合并
https://stackblitz.com/edit/xhrwsszt?file=index.html

feat(dropdown): 支持同时打开多个
