src/layui.js
获取设备信息的功能，在mac下 获取到的 device.os 未定义，增加了mac的判断。
（第一次发pull request，改动很小，建议加上windows的版本判断）
=> 获取设备信息方法完善mac的判断

doc/README.md
`<!DOCTYPE html>` 在 GitHub 在线浏览时显示不出来，加上了行内代码。
=> 优化 doc 文件夹内 md 格式

src/lay/modules/upload.js
用于点击上传按钮后  打开系统文件框时， 默认的文件筛选
例：
上传图片： accpet="image/*"
=> 加入HTML得accpet支持

src/lay/modules/layedit.js
更新layedit的build方法，使其第一个参数支持传入原生html textarea对象。
layui已经非常好用了，但是每个页面底部的layui.use 以及其内部逻辑仍然让开发着觉得麻烦和厌倦，本人在快速开发中尝试将layui的use以及其逻辑尽量自动化。在自动化过程中，发现这里有必要做一下支持。
```
<textarea class="layedit"></textarea>
...
<textarea class="layedit"></textarea>
<script>
layui.use(['jquery','layedit'],function(){
var $ = layui.$,layedit=layui.layedit;
$('.layedit').each(function(i,o){
$(o).hide();
layedit.build(o,{});
});
});
</script>
```
=> layedit build 第一个参数支持html对象

src/css/layui.css
在使用tree组件时，点击【折叠/展开】图标时，没有如预期切换状态。
在layui 2.5.6的版本没有问题，在layui 2.6.5的版本有问题，通过查看源码，发现这里多了个 ">" 选择器。
=> 修复：修复tree组件的【折叠/展开】图标在点击时不切换状态的问题

src/modules/laydate.js
input元素，土耳其语toLocaleLowerCase导致正则匹配不成功，直接使用tagName进行判断。实际上在原有逻辑上进行了扩展。
=> fix:土耳其语isInput判断

src/css/layui.css
因 ie8 不支持 `nth-child(even)` 造成那一段样式都在 ie8 无法正常显示
现将其单独出来，互相不影响。
这样，在 ie8 下除了偶数行这个样式外，都可以正常显示其他样式。
=> 修正 table 样式在 ie8 无法正常显示

src/modules/lay.js
位置计算逻辑完备性处理，可以解决在frame中底部laydate下端被遮挡的问题。
=> 位置计算逻辑完备性处理，可以解决在frame中底部laydate下端被遮挡的问题。

src/modules/table.js
通常情况下一些数据是有多行的，比如“备注”等，多行数据在后端是\n，返回到前端时由于table单元格无法处理\n换行，那么就需要手动处理问<br>，这个时候虽然支持换行了，但是如果第一行数据的长度未超过限制，就不会显示“...”展开按钮，也就无法查看完整数据。
=> table单元格存在多行文本时支持点击“...”展开

examples/form.html, src/modules/form.js
目前select分组选择框在开启搜索时，如果一个分组下的所有元素全都不匹配搜索关键字，会仍然展示该分组，影响使用体验。该提交解决了此问题。
=> 新增select分组选择框在开启搜索时支持过滤未匹配到分组元素的分组

src/modules/laydate.js
laydate 在初始化值的时候时分秒存在00的情况下无法清空 [I5GC4U](https://gitee.com/sentsim/layui/issues/I5GC4U)
修改checkValid的一处细节，时分秒判断如果超过最大值进位，那么应该是从小到大进行验证，不然有可能前面验证正常之后小单位的验证失败进位了导致大单位异常；
修改initDate关于时分秒值的判断细节修复I5GC4U提到的问题
=> 修复laydate在初始值的时分秒存在00的情况下无法情况的问题

src/modules/laydate.js
- laydate 修复min设置为天数的时候开始的时分秒为23:59:59导致设置最小为0天前也就是今天及以后的情况无法选择今天内的时间 [I5ILE8](https://gitee.com/layui/layui/issues/I5ILE8)
- laydate 修复初始化的时候如果值超出了min max的范围，弹出面板没有任何提示，如果设置了isInitValue:true触发的节点中的值跟弹出面板中选中的日期对不上的问题。
=> 修复laydate几个问题

src/css/layui.css
小白一枚,第一次做贡献,虽然非常微小,甚至可能不是最优解,请见谅.
有任何问题,请指出,打扰了.
=> 修复当开启even:true后,多行表头也会跟着进行变色.

src/modules/table.js
- table组件 height参数 - 设定容器高度 支持 #父元素ID-差值 的方式自适应父元素高度
示例: height: '#div-20'
=> table组件支持自适应父元素高度：#父元素ID-差距值

.github/pull_request_template.md, src/modules/tree.js
- 在树形组件中的**setChecked**方法中，当节点id为长数字字符串时，
设置已选择节点的复选框时，在判断节点id时添加字符串转换
````javascript
//line 763
thisId.toString() == checkedId.toString()
//lin 773
value.toString() == thisId.toString() && !input[0].checked
````
- 如果缺少类型转换的话，在使用长数字字符串作为节点id时，如果选择了某个节点，在第二次
渲染树时，会将一些未选择的节点的checkbox渲染为已选择;以下数据中，如果第一次选择了域名
节点但是没有选择概览节点，在不加类型转换时会将概览节点渲染为已选择状态。
````javascript
var data2 = [
{
title: '控制台'
, id: '113715891127976666'
, spread: true
, checked: false
, children: [
{
title: '概览'
, id: '113715891127976000'
, spread: true
, checked: false,
}, {
title: '域名'
, id: '113715891127976001'
, spread: true
, checked: false,
}, {
title: '域名1'
, id: '113715891127976002'
, spread: true
, checked: true,
},
],
}];
tree.render({
elem: '#test1'
, data: data2
, id: 'demoId2'
, showCheckbox: …
```
=> 树型组件中使用长数字字符串作为节点id时出现的渲染问题

src/modules/upload.js
使用 upload 组件 POST 上传到阿里云、腾讯云、华为云时，file 参数必须在表单域的最后一个。
所以，修改了 upload 表单域的追加顺序。
[阿里云说明](https://help.aliyun.com/document_detail/31988.html#section-0lu-03w-2z6)
[腾讯云说明](https://cloud.tencent.com/document/product/436/14690)
[华为云说明](https://support.huaweicloud.com/api-obs/obs_04_0081.html#section6)
=> 修改 upload 组件表单域的顺序

src/modules/table.js
- table 修复height配置为#divid-差值的情形中如果divid出现横杆的话无法命中正则表达式验证导致结果跟预期不一致的问题 [I5Y0SM](https://gitee.com/layui/layui/issues/I5Y0SM)
=> 修复table的height配置#divid-差值的设定中如果divid出现横杆的话无法命中的问题

src/css/modules/laydate.css, src/modules/form.js, src/modules/laydate.js
- form 修复下拉选择框form.val赋值了一个不存在于option的值的是点击弹出的选项中最后一项被选中的问题 [I63SY7](https://gitee.com/layui/layui/issues/I63SY7)
- laydate 属性calendarLinkage改名为rangeLinked
- laydate rangeLinked为auto时弹出的面板由原来的相互独立换成联动，并且空值情况下不预设当天到下个月今天这个相互独立面板的初始值效果 [测试链接](https://codepen.io/sunxiaobin89/pen/MWVByKx)
- laydate 调整如果是独立面板的时候不标注范围内的中间日期效果，跟之前的联动范围区分开来让两者更容易辨识
=> 修复一些小问题以及优化laydate日历面板的联动细节

src/modules/laydate.js
- laydate 修复日期范围在联动面板的模式下初始右面板中的日期还没有选择结束日期的时候面板就重新绘制的问题 [测试链接](https://codepen.io/sunxiaobin89/full/MWVByKx)
=> 修复日期范围在联动面板模式下初始点击右边面板的时候面板重新绘制的问题

src/modules/laydate.js
- laydate 修复点击日历面板头部的上下月上下年或者选择年月转换日历直接确认而不是跳转到对应面板的问题 [I65PMD](https://gitee.com/layui/layui/issues/I65PMD) [测试链接](https://codepen.io/sunxiaobin89/full/MWVByKx)
该问题主要是因为新增的自动切换模式的时候将判断是否需要切换模式以及是否反选等处理逻辑放在了选择日期的事件中，通过头部或者年月份面板切换年月之后默认触发了一次日期选择的事件，之前因为忘记设定一些触发条件限制导致非range模式的比如日期选择面板在点击上下月或者上下年之后直接就确认选中了而不是之前的跳转到对应的年月日期面板上待用户自定选择是否确认，同时也出现重复触发change事件的问题，以上问题已经处理完毕。
- laydate 调整选择预览的文本颜色变化细节 [I65PMD](https://gitee.com/layui/layui/issues/I65PMD) [测试链接](https://codepen.io/sunxiaobin89/full/MWVByKx)
让从无到有变化的时候文本颜色不变，文本的颜色变化初衷是让用户对于内容变化更有感，但是初始化的时候也加了一个变化的过程显得有点“多余”，会吸引掉一部分的注意力，另外一种情况比如时间范围一开始没有初始值选中之后形成一个范围的时候从无到有的变化本身就很明显了这个时候一般也不需要颜色的变换，故调整细节逻辑只有一开始有内容发生替换的时候再执行文本颜色的切换效果。
=> laydate修复bug以及调整预览文本颜色变化的细节效果

src/css/modules/laydate.css
- [] 问题修复
- [x ] 功能优化
【问题】laydate 组件底部按钮组样式，在提交之前因按钮存在内部边角，效果上像是多个紧凑一起的按钮。
【动作】保留第一个元素的左侧的 border-radius 与 最后一个元素的右侧 border-radius。让 laydate-footer-btns 看起来更像一个标准的按钮组。
【效果】修改之前：
【效果】修改之后：
=> 优化 laydate-footer-btns 样式

src/modules/table.js
- table 打印功能兼容新版 Edge [I6NZJE](https://gitee.com/layui/layui/issues/I6NZJE)
以下是不同浏览器(最新版本)在执行 `window.print()` 时的行为
| 浏览器 | `afterprint` 事件执行时机 |是否在 `window.print()` 后暂停执行代码|
| -|- |- |
| Edge | 打印完成后|  |
| Firefox | 打印开始后| ✅|
| Chrome | 打印完成后| ✅|
| IE | 打印开始后| ✅|
> Safari 因为没有设备不方便测试
在 Edge 和 Chrome 中， `printWin.print()` 后会暂停代码执行，直到打印对话框关闭。这种场景下，可能会在分配 `printWin.onafterprint` 之前引发 `onafterprint` 事件。所以需要把 `printWin.onafterprint = window.close`  放在 `printWin.print()`之前。
以下代码在除 Edge 以外的浏览器中工作良好
```
printWin.print();
printWin.close();
```
以下代码在除 Firefox 以外的浏览器中工作良好，Firefox 中无法自动关闭打印窗口
```
printWin.onafterprint = printWin.close;
printWin.print();
```
因为上述第一段代码在大多数浏览器中工作良好，并且为了避免意外(旧版浏览器不可能做全面测试)，PR 中仅对 Edge 做额外判断处理。
一些相关的信息：
1. [stackoverflow  |  Close window …
=> 优化 table 打印

src/modules/table.js, src/modules/treeTable.js
- 新增 treeTable `expandAllDefault` 是否默认展开全部节点
> `tree.view` 新增 `expandAllDefault` 用于设置是否默认展开全部节点，参数的名称和位置是否合适？
- 修复 treeTable 开启了排序并且在 `done` 回调中执行了 `expandAll` 展开全部导致死循环问题
- 修复 treeTable `reload(id)` 如果找不到 id 对应实例的时候出现报错问题 [I7CXLN](https://gitee.com/layui/layui/issues/I7CXLN)
- 修复 table 复杂表头部分字段为 `hide` 在数据异常的情况下出现表头错位的问题 
>之前的版本只有在数据正常的情况下才会对数据的表头信息进行调整导致无数据或者请求异常的时候没有更新父列的 hide 和列合并数值导致表头错位，重新调整了关键代码的执行时机修复该问题
- 加强 table `ignoreExport` 的配置支持，允许指定不排除哪些字段
>不少小伙伴提过如何导出的时候带上序号列这个问题，虽然可以自定义一个 normal 字段然后templet输出当前数据行的 LAY_NUM 但是总归不是很方便，调整之后的设置 ignoreExport 默认为 undefined 即根据表格字段是否是普通字段决定是否导出，如果为 TRUE 则会忽略，即使是一个普通的字段，如果为 false 则表示强制导致内容，对 numbers 列做了特殊处理，可以导出序号信息，其他的比如工具列也可以加上这个配置去导出所需要的内容。
- 优化 table 调整行内点击设置活动行的和执行事件的调用顺序 …
=> 修复一些问题以及新增一些功能

src/modules/dropdown.js
- 修复 dropdown 组合收缩菜单展开折叠时重置标题中所有图标的问题，关闭 [I7JAPU](https://gitee.com/layui/layui/issues/I7JAPU) 
[演示](https://codepen.io/Sight-wcg/pen/wvQrVZd)
=> 修复 dropdown 菜单(group)展开折叠时重置标题中所有图标的问题

docs/util/index.md, examples/util.html, src/modules/util.js
- 支持 `yy`, `M`,`d`,`H`,`hh`,`h`,`m`,`s`,`SSS` ,`A`格式化占位符，关闭 [I7QNPR](https://gitee.com/layui/layui/issues/I7QNPR)
**所有可用格式的列表，中括号里的字符会原样保留** 
[playground](https://codepen.io/Sight-wcg/pen/RwqdyBY)
|Format |Output | Description |
| --- | --- | --- |
|yy|23|两位数的年份|
|yyyy|2023|四位数的年份|
|M|1-12|月份，从 1 开始|
|MM|01-12|月份，两位数字|
|d|1-31|月份里的一天
|dd|01-31|月份里的一天，两位数字|
|H|0-23|小时|
|HH|00-23|小时，两位数字|
|h|1-12|小时, 12 小时制
|hh|01-12|小时, 12 小时制, 两位数字|
|A| 凌晨/早上/上午/中午/下午/晚上 | meridiem, 时间术语不太好翻译 |
|m|0-59|分钟|
|mm|00-59|分钟，两位数字|
|s|0-59|秒|
|ss|00-59|秒，两位数字|
|SSS|000-999|毫秒，三位数字|
=> 优化 `util.toDateString`， 更多格式化占位符支持

src/modules/treeTable.js
修复treeTable设置cols的type: 'numbers'折叠时不更新问题
=> 修复treeTable设置cols的type: 'numbers'折叠时不更新问题

src/modules/lay.js
修复 lay.clipboard.writeText IE8 下报错的问题，catch 是保留字
- 修复 lay.clipboard.writeText IE8 下报错的问题
=> 修复 lay.clipboard.writeText IE8 下报错的问题

examples/layer.html, src/modules/layer.js
> 请至少勾选一项
- 优化 layer 移动端定位，关闭 [I81WGC](https://gitee.com/layui/layui/issues/I81WGC)，也可能解决 [I7W9FN](https://gitee.com/layui/layui/issues/I7W9FN)
已在 Android 9 系统 webview(chrome 73)，Kiwi Browser(chrome 112)中测试通过。这应该是 jQuery 的 BUG，详细信息参考 https://github.com/jquery/jquery/pull/764
jQuery 在 2.2 中解决了这个问题，使用 $(window).outerXXX() 时和 window.innerXXX 行为一致 
https://github.com/jquery/jquery/issues/1729
https://github.com/jquery/jquery/commit/7d44d7f9e7cb73ff2b373f08cea13ea9958bb462
Before
After
【演示】https://stackblitz.com/edit/web-platform-nihidf
=> 优化 layer 移动端定位

src/modules/form.js
> 请至少勾选一项
- 新增 `lay-precision` attributes，用于设置数值精度，关闭 [I81SY4](https://gitee.com/layui/layui/issues/I81SY4)
- 失去焦点时将数据约束回范围内，解决 [I7KU6V](https://gitee.com/layui/layui/issues/I7KU6V)
- 优化加减按钮的禁用视觉效果
【演示】https://stackblitz.com/edit/web-platform-ak8hpj?file=index.html
=> 新增 `input-number`  组件 `lay-precision` attributes，优化禁用视觉效果

examples/element.html, src/css/layui.css
> 请至少勾选一项
- 修复 hr 边框宽度
2.8.18-rc.1 带有 layui-border-xxx 类的分割线比默认的宽一些
=> 修复 hr 边框宽度

src/css/layui.css, src/modules/form.js
> 请至少勾选一项
- 修复 input-number `lay-precision` 属性初始渲染时无效的问题，关闭 [I85Z5Y](https://gitee.com/layui/layui/issues/I85Z5Y)
[演示] https://stackblitz.com/edit/ovywgf-psxkna?file=index.html
=> 修复 input-number `lay-precision` 属性初始渲染时无效的问题

src/modules/treeTable.js
> 请至少勾选一项
- 修复 treeTable 数据格式为简单类型时 IE9+ 兼容问题，关闭 [I8C04Y](https://gitee.com/layui/layui/issues/I8C04Y)
IE8 仍需要添加 [Object.keys 的 polyfill](https://github.com/inexorabletash/polyfill/blob/716a3f36ca10fad032083014faf1a47c638e2502/es5.js#L111-L124)
=> 修复 treeTable 数据格式为简单类型时 IE9+ 兼容问题

src/modules/lay.js
> 请至少勾选一项
- 优化 `lay.clipboard.writeText`，没有剪贴板写入权限时使用 legacy 方法。修复 [I8D94I](https://gitee.com/layui/layui/issues/I8D94I)
【演示】https://stackblitz.com/edit/web-platform-51v1cs?file=index.html
例如现在可以在 stackblitz 的 iframe 中复制
=> 优化 `lay.clipboard.writeText`，没有剪贴板写入权限时使用 legacy 方法

src/modules/table.js
> 请至少勾选一项
- 修复 table 单元格多行展开风格，关闭展开状态时，表格行悬停状态类未移除的问题
Before
After
=> 修复 table 单元格多行展开风格，关闭展开状态时，表格行悬停状态类未移除的问题

src/css/layui.css
> 请至少勾选一项
- 修复 element.nav 在 IE8 下子菜单背景色
=> 修复 element.nav 在 IE8 下子菜单背景色

src/modules/treeTable.js
> 请至少勾选一项
- 修复 teetable 组件 `treeTable.updateNode` 更新已打开的节点时，未重新渲染表单元素的问题
[演示]https://stackblitz.com/edit/wyjrwb-98swhb?file=demo-1.json
=> fix(treetable): 修复 `treeTable.updateNode()` 更新已打开的节点时，未重新渲染表单元素的问题

src/modules/laydate.js
> 请至少勾选一项
- 修复 laydate 开启 rangeLinked 时，选择同一日期，某些情况时间会反选的问题
=> fix(laydate): 修复 laydate 开启 rangeLinked 时，选择同一日期，某些情况时间会反选的问题

src/modules/table.js
> 请至少勾选一项
- fix(table): 关闭展开状态时，未重置单元格滚动条水平位置。close [#1535](https://github.com/layui/layui/issues/1535)
=> fix(table): 关闭展开状态时，未重置单元格滚动条位置

src/modules/table.js
> 请至少勾选一项
- 新增 cssRules 补丁，为避免 DevTools 审查 iframe 通过 **srcdoc** 加载的 table 元素时导致的页面崩溃
=> fix(table): 修复 Chrome DevTools 审查 iframe srcdoc 中的 table 元素导致的页面崩溃

src/css/modules/layer.css, src/modules/layer.js
> 请至少勾选一项
- 遮罩层添加过渡效果
- 设置 hideOnClose 时支持动画效果
shade 数组类型，第三个值仅限内部使用，不在文档中公开，用于处理 layer.photos 遮罩。
https://stackblitz.com/edit/orsrjb-kf8ps8?file=index.html
close #1601
=> feat(layer): 遮罩层添加过渡效果

src/css/layui.css
> 请至少勾选一项
- fix(slider): Firefox 浏览器中拖动滑块时会选中文本的问题   closes #1714 
从 layui v2.9.6 开始有此问题，但 slider 代码逻辑并没有变化，原因不明。
=> fix(slider): Firefox 浏览器中拖动滑块时会选中文本的问题

src/modules/treeTable.js
> 请至少勾选一项
- fix(treeTable): 修复点击表头排序后，内部缓存数据和表格显示数据不一致的问题
closes #1732
Mock 在 stackblitz 运行失败，需要拉取到本地测试
=> fix(treeTable): 修复点击表头排序后，内部缓存数据和表格显示数据不一致的问题

src/modules/upload.js
> 请至少勾选一项
修复多文件上传时选择一个文件后再次点击选择按钮直接取消，再次选择同一个文件时允许加入上传排队问题
演示：
=> fix(upload): 修复多个文件上传时能选择同样文件问题

src/css/layui.css
> 请至少勾选一项
- fix(colorpicker): RGBA 颜色输入框显示不全的问题
close #1829
=> fix(colorpicker): RGBA 颜色输入框显示不全的问题

docs/laydate/examples/cell.md
> 请至少勾选一项
- 左下角自主拼接的农历信息效果很棒，但在之前的示例中(#1843)，仅在点击单元格时有效，为达到更好的效果，特对此新增事件响应：面板初始打开时、日期改变时、点击底部栏“现在”按钮时。理论上可完全替代原 `isPreview` 选项开启时的效果。
https://stackblitz.com/edit/web-platform-haqwye?file=index.html
=> docs(laydate): 优化农历预览显示的事件响应

src/modules/dropdown.js, src/modules/laydate.js, src/modules/table.js, src/modules/treeTable.js
> 请至少勾选一项
- refactor: 将 dropdown, table, treeTable 组件上的 `lay-id` 属性重命名为 `lay-${MOD_NAME}-id`, laydate 由 `layui-laydate-id` 重命名为 `lay-laydate-id`。
close #1883
=> refactor: 将部分组件上的 `lay-id` 属性重命名为 `lay-${MOD_NAME}-id`

examples/treeTable-test-reloadData.html, src/modules/table.js, src/modules/treeTable.js
> 请至少勾选一项
close #1891
- [x ] 已提供在线演示地址（如：[codepen](https://codepen.io/), [stackblitz](https://stackblitz.com/)）或无需演示
-----
<a href="https://stackblitz.com/~/github.com/jichuanan/layui/tree/jichuanan/issue1891"><img src="https://developer.stackblitz.com/img/review_pr_small.svg" alt="Review PR in StackBlitz" align="left" width="103" height="20"></a> _Submitted with [StackBlitz](https://stackblitz.com/~/github.com/jichuanan/layui/tree/jichuanan/issue1891)._
=> fix(treeTable): 修复重载数据时，指定参数 scrollPos: 'fixed' 无效的问题

src/modules/form.js
> 请至少勾选一项
- refactor(form-select): 开启 lay-creatable 时，新创建的 option 元素显示在顶部
- feat(form-select): 支持循环切换选中元素
- fix(form-select): 开启 creatable 后方向键切换选中元素偶现异常
https://github.com/layui/layui/assets/26325820/cfc48439-591e-464d-9e99-7e18f929e274
https://stackblitz.com/edit/orsrjb-ugk2tj?file=index.html
=> refactor(form-select): 开启 lay-creatable 时，新创建的 option 元素显示在顶部

docs/tab/index.md, src/css/layui.css, src/modules/element.js
> 请至少勾选一项
1. 在选项卡标题元素 `<li>` 上设置 `lay-allowclose="false"` 时单独关闭这个选项卡的删除图标
2. element.tabAdd 第二个参数新增 allowClose 选项，控制是否显示关闭图标
3. 新增 tabBeforeDelete 事件，返回 false 时阻止关闭对应的选项卡
4. 当 tab title 元素上有 lay-id 属性时，将根据 id 显示/删除对应的 content 元素，方便实现选项卡拖拽排序
5. 因为 4，事件参数中新增 id 属性
https://stackblitz.com/edit/vu45xk-ustgip?file=index.html
=> feat(tab): 增强 tab 功能

src/modules/element.js
> 请至少勾选一项
- fix(tab): 修复 lay-id 属性值中含有某些特殊字符时，可能会导致 html 标签解析异常。由 #1955 导致
close #1989
=> fix(tab): 修复 lay-id 属性值中含有某些特殊字符时，可能会导致 html 标签解析异常

docs/table/index.md, examples/table-test.html, src/modules/table.js
> 请至少勾选一项
- 单元格编辑不触发 `row, rowDouble` 
closes #2063
- 对行相关事件新增返回 jQuery event 对象
https://stackblitz.com/edit/4oq31v?file=index.html
=> refactor(table): 优化行单双击事件机制，避免与单元格编辑等事件冲突

docs/form/index.md, src/modules/form.js
> 请至少勾选一项
- feat(form-select): 弃用 `lay-search="cs"`，新增 `lay-search="{caseSensitive:false, fuzzy: false}"` 方式 
close #2115
ref #2117
https://stackblitz.com/edit/pszywd-mgqfk2?file=index.html
=> feat(form-select): 弃用 `lay-search="cs"`， 支持使用 JSON 字符串设置参数

src/modules/form.js
…ropdown 面板意外关闭
> 请至少勾选一项
- fix(form-select): 开启 `lay-append-to` 时，在 dropdown 中点击 select 面板，会导致 dropdown 面板关闭
https://stackblitz.com/edit/pszywd-zmy6ff?file=index.html
=> fix(form-select): 开启 `lay-append-to` 时，在 dropdown 中点击 select 面板，会导致 dropdown 面板关闭

docs/table/index.md, examples/table-test.html, src/modules/table.js
> 请至少勾选一项
- 继承自 #2119
closes #2116
- 修复 table 表格嵌套时，选中当前行，影响到当前行嵌套表格所有行的选中问题
- 重构 table.setRowChecked() 方法，优化循环代码
*根据测试，性能方面与 2.9.14 没有太大变化，这一项主要是代码简洁层面的优化*
> stackblitz 的静态页面，最近好像存在一些 BUG
1. table 表格嵌套: 
https://codepen.io/layui/pen/ExBmRwL
1. table 性能测试（来自 #2004）: 
https://codepen.io/layui/pen/VwJbdXO
=> refactor(table): 重构 table.setRowChecked() 方法

docs/table/examples/demo.md
将表头属性 toolbar 替换为等效属性 templet
新版本的表头属性介绍文档中已经移除了关于 toolbar 的介绍
> 请至少勾选一项
- 将表头属性 toolbar 替换为等效属性 templet
=> docs(table-demo): 更新文档

docs/table/index.md, src/modules/table.js
> 请至少勾选一项
- feat: 返回数据新增 `dataCache` 成员，即选中的原始缓存数据，包含内部特定字段。
- fix: 修复返回数据均为 `LAY_DISABLED: true` 时默认全选的问题
- closes #2229
Preview: https://stackblitz.com/edit/3wuq9m-v9dira?file=index.html,index.js
=> feat(table): 优化 table.checkStatus() 方法

docs/dropdown/detail/options.md, src/modules/dropdown.js
> 请至少勾选一项
1. 新增 closeOnClick 选项 close #2211
2. 新增 onClickOutside 回调
- 可以实现点击面板外部不关闭面板，最常见的场景就是表单填写一半时防误触
- 可以简化非当前节点渲染的第三方组件在 dropdown 中的使用
4. 修复自定义 content 的上下文菜单异常关闭问题  close #2275
https://stackblitz.com/edit/mynco9?file=index.html
=> feat(dropdown): 支持自定义自动关闭功能

src/modules/table.js
> 请至少勾选一项
- 去除表格初始加载时的横向滚动条
https://github.com/layui/layui/pull/2187#issuecomment-2372952155 这个问题没有完全修复，现在去掉初始加载时的滚动条，应该能够规避这类问题。
- 修复改变浏览器窗口大小时，空表格偶现滚动条的问题
也许能修复 #2323 。设置了 min/max width 的表格拖动窗口中偶现滚动条是正常现象，列宽计算结果如此，测试方法见代码注释。
[演示] https://stackblitz.com/edit/vzzwk2?file=index.html
=> fix(table): 修复设置列宽的一些边缘情况

src/modules/table.js
> 请至少勾选一项
- closes #1834 #2309
- Preview: https://stackblitz.com/edit/gioivx?file=index.html,index.js
=> fix(table): 修复排序且重载后 `table.cache` 数据中的 `LAY_INDEX` 丢失的问题

docs/dropdown/examples/base.md, docs/dropdown/examples/contextmenu.md, docs/table/examples/demo.md, examples/dropdown.html, src/modules/dropdown.js
> 请至少勾选一项
- 重构 面板打开与关闭的逻辑
- 调整 `closeOnClick` 选项默认值为 `true`，即点击目标元素时自动切换打开与关闭
- 修复 在元素自定义事件中创建实例并立刻显示的报错问题
- closes #2347
- Preview: https://stackblitz.com/edit/fjx38j?file=index.html,index.js
=> refactor: 重构 dropdown 打开与关闭逻辑

src/css/layui.css
> 请至少勾选一项
- fix(tab): tab 出现展开按钮时，活动选项卡底边框显示异常
已在不同屏幕缩放和浏览器缩放以及 IE8 - IE10 仿真，IE11 下测试通过
https://stackblitz.com/edit/swuvngly?file=index.html
之前
之后 
=> fix(tab): tab 出现展开按钮时，活动选项卡底边框显示异常

src/modules/table.js
#2187
> 请至少勾选一项
- fix(table): 隐藏元素内渲染 table 时获取宽度的行为回退到 2.9.17 之前
解决 https://github.com/layui/layui/discussions/2398
https://stackblitz.com/edit/tbfo5w49?file=index.js
=> fix(table): 隐藏元素内渲染 table 时获取宽度的行为回退到 2.9.9 之前

src/modules/treeTable.js
> 请至少勾选一项
- closes #2056
该问题触发原因：treeTable 的 [initData](https://github.com/layui/layui/blob/main/src/modules/treeTable.js#L549-L568) 方法中，若直接赋值 data ，`LAY_DATA_INDEX` 字段未对 data 进行分页赋值索引，导致顶层节点 `lay-data-index` 属性值不匹配，getNodeDataByIndex 方法无法获取到对应的数据，进而导致报错。
[演示]：https://stackblitz.com/edit/kqvd3s4z?file=index.html
=> fix(treeTable): 修复直接赋值 `data` 时切换分页出现报错的问题

src/modules/form.js
Reverts layui/layui#2428
如果复选框有同名隐藏表单元素用来获取未选中的值，将会获取到错误的结果。
=> Revert  "feat(form): 相同 name 的 checkbox，将值序列化为数组"

src/modules/form.js
> 请至少勾选一项
- fix(form): 修复 select 未选中时 form.val 获取到的值为 null 的问题
close #2473
https://stackblitz.com/edit/kfavzzs1?file=index.js
=> fix(form): 修复 select 未选中时 form.val 获取到的值为 null 的问题

src/css/layui.css, src/css/modules/code.css
> 请至少勾选一项
- 在 CSS 每一处使用了等距字体的 `font-family` 末尾增加了 `monospace` 作为前面字体未生效的 fallback, 以优化在部分 Linux 桌面的使用体验
=> fix(css): monospace font fallback

docs/class/index.md
| layui-border-box | 设置元素及其所有子元素均为 `box-sizing: border-box` 模型的容器 |
> 请至少勾选一项
文档说明--公共类--layui-border-box写错了
=> docs: 更正 class 公共类文档错误

src/css/layui.css
> 请至少勾选一项
- 优化checkbox标签风格选中且禁用时的显示
- 之前：选中禁用时仍显示绿色，且hover时会让选中看不见
- 现在：选中禁用时优化为灰色，且hover时不影响显示
=> fix(form-checkbox): 优化 checkbox 标签风格选中且禁用时的显示

docs/component/detail/options.md, src/css/layui.css, src/modules/component.js, src/modules/tabs.js
> 请至少勾选一项
- feat(component): 新增 cache 原型方法，用于元素缓存操作
- fix(component): 修复 reload 时传入的选项未正确合并的问题
- fix(component): 优化元素 lay-options 属性上的配置在重载时的优先级
- fix: 优化 tabs 重载时未按照传入的 closable 正确渲染可关闭状态
=> feat: 优化 component, tabs 若干功能

src/modules/layer.js
> 请至少勾选一项
- fix(layer): getFrameIndex 行为与 2.x 保持一致。 参考 https://github.com/jquery/jquery/pull/1682
close #2590
=> fix(layer): getFrameIndex 行为与 2.9 保持一致

docs/component/index.md, src/modules/component.js, src/modules/tabs.js
> 请至少勾选一项
- 新增 `component.removeInst()` 基础方法，用于移除缓存中的组件实例
- 新增 `component.getAllInst()` 方法（暂不公开使用）
- 调整 `component.getThis` → `component.getInst`，为了与 `laydate.getInst` 保持一致。
=> feat: 新增 `component.removeInst()` 基础方法，用于移除缓存中的组件实例

docs/tabs/index.md, src/modules/tabs.js
> 请至少勾选一项
- 新增 `tabs.add()` 的 `active` 选项，用于是否将新增项设置为活动标签
- closes #2604
=> feat(tabs): 为 tabs.add 新增 active 选项

docs/component/detail/options.md, src/modules/component.js, src/modules/tabs.js
> 请至少勾选一项
- 剔除 isRenderOnEvent, isRenderWithoutElem 选项。将定制权交给 `render` 函数，提升组件可扩展性
- 关联：https://github.com/layui/layui/pull/2566#issuecomment-2727454117
- 为 `component.removeInst()` 增加对 `component.cache.id` 缓存的移除。此项不必写入更新日志中。
=> refactor(component): 剔除 isRenderOnEvent, isRenderWithoutElem 选项

src/layui.js
> 请至少勾选一项
- fix(layui): 修复 layui.link 重复执行时不触发回调函数的问题
重复执行时新创建的 link 标签不会添加到页面中，加载完成事件无法触发，这会导致开发版本中 laydate 无法渲染。
这个 PR 在 link 元素对象上添加了一个私有的 `__lay_readyState__` 标识加载状态，若加载完成直接执行回调。
=> fix(layui): 修复 layui.link 重复执行时不触发回调函数的问题

src/modules/form.js, src/modules/lay.js
> 请至少勾选一项
- fix(form-select): 修复 `checkbox/radio` 在 WebKit/537.36 的异常
无法获取元素属性描述符，回退到 IE8 的解决方案即可
只测试了 WebKit/537，WebKit/538 应该没理由会把 input 元素的属性描述符 configurable 设置为 false，
因此这和 #2633 可能是两个不同的问题，需要等待进一步的确认。
```
jQuery.Deferred exception: Cannot read property 'set' of undefined TypeError: Cannot read property 'set' of undefined
at <error: TypeError: Accessing selectionDirection on an input element that cannot have a selection.>
at HTMLFormElement.<anonymous> (http://127.0.0.1:5501/src/modules/form.js:122:31)
at Function.jQuery.extend.each (http://127.0.0.1:5501/src/modules/jquery.js:383:19)
at jQuery.fn.jQuery.each (http://127.0.0.1:5501/src/modules/jquery.js:205:17)
at Form.val (http://127.0.0.1:5501/src/modules/form.js:105:14)
at null.<anonymous> …
```
=> fix(form-select): 修复 `checkbox/radio` 在 WebKit/537.36 的异常

examples/form.html, src/modules/form.js
> 请至少勾选一项
- closes #2656, closes #2653, closes #2336
- 演示：https://stackblitz.com/edit/bnzsy1sz?file=index.html
=> fix(form): 修复 select 组件的字符转义问题

src/modules/form.js
> 请至少勾选一项
- fix(form-select): 修复 option 两端的 Unicode 空格(U+00A0)被去除的问题  close #2670
https://stackblitz.com/edit/vqbretlz?file=index.html
1. ddElement.innerText 取 optionElement.innerText 原始值，不做 trim，并将 optionElement.text 存储在 dd 元素的 lay-label 属性上
option.text: https://html.spec.whatwg.org/multipage/form-elements.html#dom-option-text
3. input 显示值取 optionElement.text，和原生 select 保持一致
4. 搜索时由比较 innerText 变为比较 text，理论上对搜索不会有影响
=> fix(form-select): 修复 option 两端的 Unicode 空格(U+00A0)被去除的问题

docs/tabs/examples/demo.md, docs/tabs/index.md, examples/tabs.html, src/modules/tabs.js
> 请至少勾选一项
- 优化 `header` 选项初始值的判断，允许数组为空
- resolves #2677
- 优化 `tabs.getBodyItem()` 第二个参数，可接受索引或 `lay-id` 值
- refs https://github.com/layui/layui/issues/2635#issuecomment-2820344545 
- 优化 `tabs.add()` 的 `done` 回调，参数新增包含新标签项元素
- refs #2652
- 优化 `tabs.change()` 方法，标签项打乱顺序时仍可通过 `lay-id` 切换
=> feat(tabs): 优化若干功能

src/css/layui.css
> 请至少勾选一项
- fix(table): 修复设置 `even:true` 时，行选中背景色异常, close #2767
之前
之后
=> fix(table): 修复设置 `even:true` 时，行选中背景色异常

src/modules/tabs.js
> 请至少勾选一项
- fix(tabs): 修复获取标签内容项 lay-id 不存在时会返回最后一项的问题
close #2804
=> fix(tabs): 修复获取标签内容项 lay-id 不存在时会返回最后一项的问题

docs/versions.md, src/modules/dropdown.js, src/modules/form.js, src/modules/lay.js, src/modules/table.js
…ver`
> 请至少勾选一项
- chore: 重命名` lay._createResizeObserver` 为 `lay.createSharedResizeObserver`
=> chore: 重命名` lay._createResizeObserver` 为 `lay.createSharedResizeObserver`
